# Triage Results
Script/NB for generating the lookup of the triage results. For every project in
the test set of each of ASF, EF, OF, and GH we will predict on the best model of
each. Later, we can run the triage model and pick the output label.

Output columns will be:
- Incubator
- Project
- Outcome
- ASF Pred
- EF Pred
- OF Pred
- GF Pred
- Triage Incubator Pred (to be done later)

***

## Env Setup

In [1]:
import decalfc as pex
from decalfc.abstractions.modeldata import *
from decalfc.abstractions.tsmodel import *
from decalfc.pipeline.inference import *

import numpy as np

/home/aashok17/miniconda3/envs/pex/lib/python3.11/site-packages/torch/cuda/__init__.py:182: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0

INFO: Pandarallel will run on 6 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [2]:
incs = ["apache", "eclipse", "osgeo", "github"]
model_archs = dict(zip(incs, ["BLSTM", "BLSTM", "DLSTM", "DLSTM"]))

***
## Finding the Median Fold Projects

In [3]:
def find_median_fold(inc: str, k: int=5, model_arch: str="BLSTM", **kwargs) -> tuple[set[str], set[str]]:
    """
    Finds the median fold from the cross-validation, i.e. the projects
    themselves that we used to generate the CV results reported in the paper.
    """
    
    # === train the models for this fold === #
    # load all data in a folds iterator
    folds = ModelData.gen_k_folds(
        transfer_strategy=f"{inc} --> {inc}",
        transform_kwargs=kwargs.get("transform-kwargs", dict()),
        nfolds=k,
        yield_projs=True
    )
    
    # store only the median trial in the perf database; we'll create a temporary
    # perf-db for this kfold trial, pick the median, and update the actual perf
    # db
    temp_perf_path = f""
    pfd = PerfData(temp_perf_path)
    fold_projs: list[tuple[set[str], set[str]]] = list()
    perfs = list()

    # train model & test for each fold
    for fold, projs in folds:
        ## grab sample tensor, i.e. first tensor we have
        sample_tensor = fold.tensors["train"]["x"][0]
            
        ## ensure some hyperparams
        hyperparams = {"input_size": sample_tensor.shape[1]}
        hyperparams.update(kwargs.get("hyperparams", dict()))

        ## build model
        model = TimeSeriesModel(
            model_arch=model_arch,
            hyperparams=hyperparams
        )
        
        ## train & test
        print(len(fold.tensors["train"]["y"]), len(fold.tensors["test"]["y"]))
        print(len(projs[0]), len(projs[1]))
        model.train(fold)
        model.test(fold)
        
        ## track perf
        pfd._add_entry(
            transfer_strat=f"{inc} --> {inc}",
            model_arch=model_arch,
            preds=model.preds,
            targets=model.targets,
            export_db=False
        )
        perfs.append(pfd.data[(pfd.data.metric == "f1-score") & (pfd.data.label == "weighted avg")]["perf"].iloc[-1])
        
        ## add projs
        fold_projs.append(projs)
    
    # median finding
    median_idx = np.where(perfs == np.median(perfs))[0][0]

    # export train and test for median fold
    return fold_projs[median_idx]

In [4]:
median_folds = {
    inc: find_median_fold(inc=inc[0].upper(), model_arch=model_archs[inc])
    for inc in incs
}

/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `a --> a`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 100.00% of the data reserved for testing
Log [0.0h, 0.0m, 0.000s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.016s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.069s]> Generating tensors

<Tensor Info For Apache>

100%|██████████| 263/263 [00:00<00:00, 19328.93it/s]
100%|██████████| 263/263 [00:00<00:00, 57636.34it/s]

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `a --> a`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>

211 52
211 52

100%|██████████| 211/211 [00:01<00:00, 148.46it/s]

Log [0.0h, 0.0m, 2.213s]> Epoch [1/100] | loss: 0.0524, test loss: 0.0425, test acc: 0.8462 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 163.70it/s]

Log [0.0h, 0.0m, 1.351s]> Epoch [2/100] | loss: 0.0338, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.38it/s]

Log [0.0h, 0.0m, 1.378s]> Epoch [3/100] | loss: 0.0326, test loss: 0.0425, test acc: 0.8462 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 154.48it/s]

Log [0.0h, 0.0m, 1.426s]> Epoch [4/100] | loss: 0.0332, test loss: 0.0432, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 157.60it/s]

Log [0.0h, 0.0m, 1.398s]> Epoch [5/100] | loss: 0.0317, test loss: 0.0469, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 165.70it/s]

Log [0.0h, 0.0m, 1.335s]> Epoch [6/100] | loss: 0.0383, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 155.73it/s]

Log [0.0h, 0.0m, 1.417s]> Epoch [7/100] | loss: 0.0319, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.56it/s]

Log [0.0h, 0.0m, 1.376s]> Epoch [8/100] | loss: 0.0323, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 157.54it/s]

Log [0.0h, 0.0m, 1.399s]> Epoch [9/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 157.89it/s]

Log [0.0h, 0.0m, 1.397s]> Epoch [10/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.48it/s]

Log [0.0h, 0.0m, 1.408s]> Epoch [11/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.27it/s]

Log [0.0h, 0.0m, 1.393s]> Epoch [12/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 165.45it/s]

Log [0.0h, 0.0m, 1.344s]> Epoch [13/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 167.45it/s]

Log [0.0h, 0.0m, 1.322s]> Epoch [14/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 164.36it/s]

Log [0.0h, 0.0m, 1.343s]> Epoch [15/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 162.76it/s]

Log [0.0h, 0.0m, 1.367s]> Epoch [16/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 156.82it/s]

Log [0.0h, 0.0m, 1.414s]> Epoch [17/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 164.93it/s]

Log [0.0h, 0.0m, 1.338s]> Epoch [18/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 163.53it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/perfdata.py:713: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data = pd.concat([self.data, new_entries], ignore_index=True)

Log [0.0h, 0.0m, 1.350s]> Epoch [19/100] | loss: 0.0315, test loss: 0.0396, test acc: 0.8846 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([13, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `a --> a`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
211 52
211 52

100%|██████████| 211/211 [00:01<00:00, 161.77it/s]

Log [0.0h, 0.0m, 1.393s]> Epoch [1/100] | loss: 0.0477, test loss: 0.0723, test acc: 0.8077 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 164.27it/s]

Log [0.0h, 0.0m, 1.349s]> Epoch [2/100] | loss: 0.0419, test loss: 0.0388, test acc: 0.8654 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 164.45it/s]

Log [0.0h, 0.0m, 1.344s]> Epoch [3/100] | loss: 0.0346, test loss: 0.0446, test acc: 0.7885 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 162.35it/s]

Log [0.0h, 0.0m, 1.358s]> Epoch [4/100] | loss: 0.0391, test loss: 0.0374, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 150.34it/s]

Log [0.0h, 0.0m, 1.471s]> Epoch [5/100] | loss: 0.0383, test loss: 0.0417, test acc: 0.8269 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.20it/s]

Log [0.0h, 0.0m, 1.418s]> Epoch [6/100] | loss: 0.0335, test loss: 0.0374, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 157.47it/s]

Log [0.0h, 0.0m, 1.405s]> Epoch [7/100] | loss: 0.0331, test loss: 0.0374, test acc: 0.8846 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.15it/s]

Log [0.0h, 0.0m, 1.386s]> Epoch [8/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 163.49it/s]

Log [0.0h, 0.0m, 1.351s]> Epoch [9/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.71it/s]

Log [0.0h, 0.0m, 1.372s]> Epoch [10/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.12it/s]

Log [0.0h, 0.0m, 1.420s]> Epoch [11/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.29it/s]

Log [0.0h, 0.0m, 1.418s]> Epoch [12/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 161.91it/s]

Log [0.0h, 0.0m, 1.362s]> Epoch [13/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 152.52it/s]

Log [0.0h, 0.0m, 1.466s]> Epoch [14/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 161.47it/s]

Log [0.0h, 0.0m, 1.364s]> Epoch [15/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 166.23it/s]

Log [0.0h, 0.0m, 1.326s]> Epoch [16/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.68it/s]

Log [0.0h, 0.0m, 1.380s]> Epoch [17/100] | loss: 0.0331, test loss: 0.0360, test acc: 0.9038 | lr: 0.001000
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([15, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `a --> a`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
211 52
211 52

100%|██████████| 211/211 [00:01<00:00, 165.88it/s]

Log [0.0h, 0.0m, 1.344s]> Epoch [1/100] | loss: 0.0488, test loss: 0.0469, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 165.48it/s]

Log [0.0h, 0.0m, 1.339s]> Epoch [2/100] | loss: 0.0389, test loss: 0.0418, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 161.00it/s]

Log [0.0h, 0.0m, 1.370s]> Epoch [3/100] | loss: 0.0404, test loss: 0.0432, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 161.16it/s]

Log [0.0h, 0.0m, 1.365s]> Epoch [4/100] | loss: 0.0354, test loss: 0.0418, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 165.09it/s]

Log [0.0h, 0.0m, 1.336s]> Epoch [5/100] | loss: 0.0347, test loss: 0.0432, test acc: 0.9038 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 162.99it/s]

Log [0.0h, 0.0m, 1.355s]> Epoch [6/100] | loss: 0.0339, test loss: 0.0418, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.93it/s]

Log [0.0h, 0.0m, 1.369s]> Epoch [7/100] | loss: 0.0331, test loss: 0.0418, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 163.96it/s]

Log [0.0h, 0.0m, 1.345s]> Epoch [8/100] | loss: 0.0331, test loss: 0.0367, test acc: 0.9423 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 162.47it/s]

Log [0.0h, 0.0m, 1.355s]> Epoch [9/100] | loss: 0.0330, test loss: 0.0331, test acc: 0.9423 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 167.50it/s]

Log [0.0h, 0.0m, 1.327s]> Epoch [10/100] | loss: 0.0398, test loss: 0.0367, test acc: 0.9423 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 163.02it/s]

Log [0.0h, 0.0m, 1.360s]> Epoch [11/100] | loss: 0.0354, test loss: 0.0367, test acc: 0.9423 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.10it/s]

Log [0.0h, 0.0m, 1.393s]> Epoch [12/100] | loss: 0.0400, test loss: 0.0439, test acc: 0.8462 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 158.90it/s]

Log [0.0h, 0.0m, 1.384s]> Epoch [13/100] | loss: 0.0331, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 165.08it/s]

Log [0.0h, 0.0m, 1.344s]> Epoch [14/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.80it/s]

Log [0.0h, 0.0m, 1.369s]> Epoch [15/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 157.71it/s]

Log [0.0h, 0.0m, 1.396s]> Epoch [16/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 164.15it/s]

Log [0.0h, 0.0m, 1.344s]> Epoch [17/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.95it/s]

Log [0.0h, 0.0m, 1.368s]> Epoch [18/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.97it/s]

Log [0.0h, 0.0m, 1.377s]> Epoch [19/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 165.15it/s]

Log [0.0h, 0.0m, 1.335s]> Epoch [20/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 164.71it/s]

Log [0.0h, 0.0m, 1.337s]> Epoch [21/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 159.20it/s]

Log [0.0h, 0.0m, 1.385s]> Epoch [22/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 155.95it/s]

Log [0.0h, 0.0m, 1.419s]> Epoch [23/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 162.37it/s]

Log [0.0h, 0.0m, 1.358s]> Epoch [24/100] | loss: 0.0319, test loss: 0.0381, test acc: 0.9231 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([15, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `a --> a`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
211 52
211 52

100%|██████████| 211/211 [00:01<00:00, 156.36it/s]

Log [0.0h, 0.0m, 1.425s]> Epoch [1/100] | loss: 0.0533, test loss: 0.0389, test acc: 0.9615 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.11it/s]

Log [0.0h, 0.0m, 1.388s]> Epoch [2/100] | loss: 0.0434, test loss: 0.0316, test acc: 0.9615 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 152.59it/s]

Log [0.0h, 0.0m, 1.462s]> Epoch [3/100] | loss: 0.0361, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 147.41it/s]

Log [0.0h, 0.0m, 1.490s]> Epoch [4/100] | loss: 0.0372, test loss: 0.0316, test acc: 0.9615 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 147.62it/s]

Log [0.0h, 0.0m, 1.501s]> Epoch [5/100] | loss: 0.0401, test loss: 0.0440, test acc: 0.9423 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 155.53it/s]

Log [0.0h, 0.0m, 1.434s]> Epoch [6/100] | loss: 0.0417, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.49it/s]

Log [0.0h, 0.0m, 1.409s]> Epoch [7/100] | loss: 0.0357, test loss: 0.0302, test acc: 0.9808 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 166.54it/s]

Log [0.0h, 0.0m, 1.327s]> Epoch [8/100] | loss: 0.0347, test loss: 0.0302, test acc: 0.9808 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 161.06it/s]

Log [0.0h, 0.0m, 1.369s]> Epoch [9/100] | loss: 0.0368, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 158.51it/s]

Log [0.0h, 0.0m, 1.401s]> Epoch [10/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 164.00it/s]

Log [0.0h, 0.0m, 1.354s]> Epoch [11/100] | loss: 0.0342, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.65it/s]

Log [0.0h, 0.0m, 1.372s]> Epoch [12/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.86it/s]

Log [0.0h, 0.0m, 1.370s]> Epoch [13/100] | loss: 0.0335, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 163.64it/s]

Log [0.0h, 0.0m, 1.354s]> Epoch [14/100] | loss: 0.0370, test loss: 0.0287, test acc: 1.0000 | lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 165.40it/s]

Log [0.0h, 0.0m, 1.333s]> Epoch [15/100] | loss: 0.0364, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 165.97it/s]

Log [0.0h, 0.0m, 1.329s]> Epoch [16/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 155.87it/s]

Log [0.0h, 0.0m, 1.422s]> Epoch [17/100] | loss: 0.0345, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 162.54it/s]

Log [0.0h, 0.0m, 1.356s]> Epoch [18/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 161.23it/s]

Log [0.0h, 0.0m, 1.371s]> Epoch [19/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 161.61it/s]

Log [0.0h, 0.0m, 1.363s]> Epoch [20/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 166.92it/s]

Log [0.0h, 0.0m, 1.330s]> Epoch [21/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 159.74it/s]

Log [0.0h, 0.0m, 1.384s]> Epoch [22/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500

100%|██████████| 211/211 [00:01<00:00, 164.64it/s]

Log [0.0h, 0.0m, 1.339s]> Epoch [23/100] | loss: 0.0338, test loss: 0.0287, test acc: 1.0000 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([15, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `a --> a`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	apache dataset, version tech: 1, social: 1 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
208 55
208 55

100%|██████████| 208/208 [00:01<00:00, 169.06it/s]

Log [0.0h, 0.0m, 1.308s]> Epoch [1/100] | loss: 0.0496, test loss: 0.0435, test acc: 0.9091 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 157.42it/s]

Log [0.0h, 0.0m, 1.385s]> Epoch [2/100] | loss: 0.0499, test loss: 0.0380, test acc: 0.8909 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 159.03it/s]

Log [0.0h, 0.0m, 1.380s]> Epoch [3/100] | loss: 0.0369, test loss: 0.0326, test acc: 0.9636 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 146.30it/s]

Log [0.0h, 0.0m, 1.483s]> Epoch [4/100] | loss: 0.0361, test loss: 0.0470, test acc: 0.9091 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 156.56it/s]

Log [0.0h, 0.0m, 1.389s]> Epoch [5/100] | loss: 0.0353, test loss: 0.0305, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 165.59it/s]

Log [0.0h, 0.0m, 1.317s]> Epoch [6/100] | loss: 0.0380, test loss: 0.0326, test acc: 0.9636 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 167.07it/s]

Log [0.0h, 0.0m, 1.310s]> Epoch [7/100] | loss: 0.0336, test loss: 0.0278, test acc: 0.9818 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 155.51it/s]

Log [0.0h, 0.0m, 1.399s]> Epoch [8/100] | loss: 0.0338, test loss: 0.0339, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 165.28it/s]

Log [0.0h, 0.0m, 1.328s]> Epoch [9/100] | loss: 0.0345, test loss: 0.0339, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 154.98it/s]

Log [0.0h, 0.0m, 1.402s]> Epoch [10/100] | loss: 0.0345, test loss: 0.0339, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 158.59it/s]

Log [0.0h, 0.0m, 1.371s]> Epoch [11/100] | loss: 0.0345, test loss: 0.0339, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 154.78it/s]

Log [0.0h, 0.0m, 1.406s]> Epoch [12/100] | loss: 0.0345, test loss: 0.0339, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 158.97it/s]

Log [0.0h, 0.0m, 1.381s]> Epoch [13/100] | loss: 0.0345, test loss: 0.0339, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 157.36it/s]

Log [0.0h, 0.0m, 1.381s]> Epoch [14/100] | loss: 0.0345, test loss: 0.0339, test acc: 0.9455 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 159.10it/s]

Log [0.0h, 0.0m, 1.369s]> Epoch [15/100] | loss: 0.0345, test loss: 0.0291, test acc: 0.9636 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 160.56it/s]

Log [0.0h, 0.0m, 1.365s]> Epoch [16/100] | loss: 0.0345, test loss: 0.0291, test acc: 0.9636 | lr: 0.001000

100%|██████████| 208/208 [00:01<00:00, 154.54it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 1.415s]> Epoch [17/100] | loss: 0.0345, test loss: 0.0291, test acc: 0.9636 | lr: 0.001000
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([15, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `e --> e`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing
Log [0.0h, 0.0m, 0.000s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.007s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.032s]> Generating tensors

<Tensor Info For Eclipse>

100%|██████████| 139/139 [00:00<00:00, 19372.91it/s]
100%|██████████| 139/139 [00:00<00:00, 39776.78it/s]

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `e --> e`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
112 27
112 27

100%|██████████| 112/112 [00:00<00:00, 152.82it/s]

Log [0.0h, 0.0m, 0.772s]> Epoch [1/100] | loss: 0.0402, test loss: 0.0616, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 157.00it/s]

Log [0.0h, 0.0m, 0.754s]> Epoch [2/100] | loss: 0.0414, test loss: 0.0616, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 159.57it/s]

Log [0.0h, 0.0m, 0.735s]> Epoch [3/100] | loss: 0.0380, test loss: 0.0546, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 164.07it/s]

Log [0.0h, 0.0m, 0.722s]> Epoch [4/100] | loss: 0.0331, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 156.09it/s]

Log [0.0h, 0.0m, 0.757s]> Epoch [5/100] | loss: 0.0393, test loss: 0.0616, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 162.88it/s]

Log [0.0h, 0.0m, 0.721s]> Epoch [6/100] | loss: 0.0354, test loss: 0.0616, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 162.76it/s]

Log [0.0h, 0.0m, 0.724s]> Epoch [7/100] | loss: 0.0352, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 156.39it/s]

Log [0.0h, 0.0m, 0.755s]> Epoch [8/100] | loss: 0.0306, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 161.72it/s]

Log [0.0h, 0.0m, 0.727s]> Epoch [9/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 159.83it/s]

Log [0.0h, 0.0m, 0.734s]> Epoch [10/100] | loss: 0.0298, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 161.99it/s]

Log [0.0h, 0.0m, 0.726s]> Epoch [11/100] | loss: 0.0296, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 150.80it/s]

Log [0.0h, 0.0m, 0.782s]> Epoch [12/100] | loss: 0.0318, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 152.56it/s]

Log [0.0h, 0.0m, 0.767s]> Epoch [13/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 153.64it/s]

Log [0.0h, 0.0m, 0.764s]> Epoch [14/100] | loss: 0.0313, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 148.52it/s]

Log [0.0h, 0.0m, 0.788s]> Epoch [15/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 150.22it/s]

Log [0.0h, 0.0m, 0.779s]> Epoch [16/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 159.68it/s]

Log [0.0h, 0.0m, 0.736s]> Epoch [17/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 164.95it/s]

Log [0.0h, 0.0m, 0.713s]> Epoch [18/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 164.89it/s]

Log [0.0h, 0.0m, 0.718s]> Epoch [19/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 163.05it/s]

Log [0.0h, 0.0m, 0.720s]> Epoch [20/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 163.60it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/perfdata.py:713: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data = pd.concat([self.data, new_entries], ignore_index=True)

Log [0.0h, 0.0m, 0.717s]> Epoch [21/100] | loss: 0.0312, test loss: 0.0519, test acc: 0.8889 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([66, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `e --> e`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
112 27
112 27

100%|██████████| 112/112 [00:00<00:00, 167.37it/s]

Log [0.0h, 0.0m, 0.711s]> Epoch [1/100] | loss: 0.0444, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 165.50it/s]

Log [0.0h, 0.0m, 0.713s]> Epoch [2/100] | loss: 0.0431, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 145.70it/s]

Log [0.0h, 0.0m, 0.805s]> Epoch [3/100] | loss: 0.0431, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 143.65it/s]

Log [0.0h, 0.0m, 0.813s]> Epoch [4/100] | loss: 0.0400, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 158.62it/s]

Log [0.0h, 0.0m, 0.742s]> Epoch [5/100] | loss: 0.0381, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 171.91it/s]

Log [0.0h, 0.0m, 0.692s]> Epoch [6/100] | loss: 0.0367, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 172.59it/s]

Log [0.0h, 0.0m, 0.684s]> Epoch [7/100] | loss: 0.0379, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 169.23it/s]

Log [0.0h, 0.0m, 0.698s]> Epoch [8/100] | loss: 0.0366, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 156.59it/s]

Log [0.0h, 0.0m, 0.749s]> Epoch [9/100] | loss: 0.0367, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 165.81it/s]

Log [0.0h, 0.0m, 0.710s]> Epoch [10/100] | loss: 0.0359, test loss: 0.0491, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 156.29it/s]

Log [0.0h, 0.0m, 0.758s]> Epoch [11/100] | loss: 0.0360, test loss: 0.0351, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 154.84it/s]

Log [0.0h, 0.0m, 0.758s]> Epoch [12/100] | loss: 0.0368, test loss: 0.0519, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 155.61it/s]

Log [0.0h, 0.0m, 0.757s]> Epoch [13/100] | loss: 0.0277, test loss: 0.0434, test acc: 0.7778 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 151.51it/s]

Log [0.0h, 0.0m, 0.780s]> Epoch [14/100] | loss: 0.0251, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 151.04it/s]

Log [0.0h, 0.0m, 0.777s]> Epoch [15/100] | loss: 0.0236, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 154.01it/s]

Log [0.0h, 0.0m, 0.768s]> Epoch [16/100] | loss: 0.0226, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 150.83it/s]

Log [0.0h, 0.0m, 0.778s]> Epoch [17/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 152.58it/s]

Log [0.0h, 0.0m, 0.768s]> Epoch [18/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 153.24it/s]

Log [0.0h, 0.0m, 0.767s]> Epoch [19/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 163.55it/s]

Log [0.0h, 0.0m, 0.719s]> Epoch [20/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 159.74it/s]

Log [0.0h, 0.0m, 0.740s]> Epoch [21/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 153.69it/s]

Log [0.0h, 0.0m, 0.763s]> Epoch [22/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 161.17it/s]

Log [0.0h, 0.0m, 0.729s]> Epoch [23/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 161.87it/s]

Log [0.0h, 0.0m, 0.730s]> Epoch [24/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 150.03it/s]

Log [0.0h, 0.0m, 0.782s]> Epoch [25/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 163.70it/s]

Log [0.0h, 0.0m, 0.720s]> Epoch [26/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 159.87it/s]

Log [0.0h, 0.0m, 0.738s]> Epoch [27/100] | loss: 0.0225, test loss: 0.0379, test acc: 0.8519 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 161.16it/s]

Log [0.0h, 0.0m, 0.731s]> Epoch [28/100] | loss: 0.0224, test loss: 0.0379, test acc: 0.8519 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([10, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `e --> e`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
112 27
112 27

100%|██████████| 112/112 [00:00<00:00, 157.46it/s]

Log [0.0h, 0.0m, 0.750s]> Epoch [1/100] | loss: 0.0483, test loss: 0.0267, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 152.39it/s]

Log [0.0h, 0.0m, 0.781s]> Epoch [2/100] | loss: 0.0414, test loss: 0.0239, test acc: 0.9630 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 155.88it/s]

Log [0.0h, 0.0m, 0.766s]> Epoch [3/100] | loss: 0.0459, test loss: 0.0267, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 155.71it/s]

Log [0.0h, 0.0m, 0.767s]> Epoch [4/100] | loss: 0.0407, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 151.63it/s]

Log [0.0h, 0.0m, 0.773s]> Epoch [5/100] | loss: 0.0371, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 157.42it/s]

Log [0.0h, 0.0m, 0.746s]> Epoch [6/100] | loss: 0.0319, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 155.83it/s]

Log [0.0h, 0.0m, 0.765s]> Epoch [7/100] | loss: 0.0317, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 158.26it/s]

Log [0.0h, 0.0m, 0.755s]> Epoch [8/100] | loss: 0.0310, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 149.53it/s]

Log [0.0h, 0.0m, 0.787s]> Epoch [9/100] | loss: 0.0356, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 145.36it/s]

Log [0.0h, 0.0m, 0.804s]> Epoch [10/100] | loss: 0.0383, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 147.05it/s]

Log [0.0h, 0.0m, 0.795s]> Epoch [11/100] | loss: 0.0357, test loss: 0.0267, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 143.70it/s]

Log [0.0h, 0.0m, 0.819s]> Epoch [12/100] | loss: 0.0320, test loss: 0.0351, test acc: 0.8148 | lr: 0.001000

100%|██████████| 112/112 [00:01<00:00, 99.18it/s]

Log [0.0h, 0.0m, 1.178s]> Epoch [13/100] | loss: 0.0303, test loss: 0.0295, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 128.88it/s]

Log [0.0h, 0.0m, 0.911s]> Epoch [14/100] | loss: 0.0277, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 124.84it/s]

Log [0.0h, 0.0m, 0.933s]> Epoch [15/100] | loss: 0.0275, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 133.21it/s]

Log [0.0h, 0.0m, 0.880s]> Epoch [16/100] | loss: 0.0276, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 154.75it/s]

Log [0.0h, 0.0m, 0.764s]> Epoch [17/100] | loss: 0.0275, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 145.23it/s]

Log [0.0h, 0.0m, 0.810s]> Epoch [18/100] | loss: 0.0274, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 136.65it/s]

Log [0.0h, 0.0m, 0.860s]> Epoch [19/100] | loss: 0.0274, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:01<00:00, 110.65it/s]

Log [0.0h, 0.0m, 1.053s]> Epoch [20/100] | loss: 0.0276, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 132.18it/s]

Log [0.0h, 0.0m, 0.888s]> Epoch [21/100] | loss: 0.0276, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 134.54it/s]

Log [0.0h, 0.0m, 0.871s]> Epoch [22/100] | loss: 0.0275, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 133.49it/s]

Log [0.0h, 0.0m, 0.885s]> Epoch [23/100] | loss: 0.0275, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 128.81it/s]

Log [0.0h, 0.0m, 0.916s]> Epoch [24/100] | loss: 0.0271, test loss: 0.0295, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 122.05it/s]

Log [0.0h, 0.0m, 0.959s]> Epoch [25/100] | loss: 0.0277, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 143.01it/s]

Log [0.0h, 0.0m, 0.816s]> Epoch [26/100] | loss: 0.0275, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 159.58it/s]

Log [0.0h, 0.0m, 0.735s]> Epoch [27/100] | loss: 0.0274, test loss: 0.0323, test acc: 0.8519 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 159.34it/s]

Log [0.0h, 0.0m, 0.737s]> Epoch [28/100] | loss: 0.0275, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 154.91it/s]

Log [0.0h, 0.0m, 0.771s]> Epoch [29/100] | loss: 0.0253, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 146.64it/s]

Log [0.0h, 0.0m, 0.811s]> Epoch [30/100] | loss: 0.0252, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 153.51it/s]

Log [0.0h, 0.0m, 0.763s]> Epoch [31/100] | loss: 0.0250, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 167.66it/s]

Log [0.0h, 0.0m, 0.701s]> Epoch [32/100] | loss: 0.0247, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 153.66it/s]

Log [0.0h, 0.0m, 0.765s]> Epoch [33/100] | loss: 0.0230, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 149.40it/s]

Log [0.0h, 0.0m, 0.791s]> Epoch [34/100] | loss: 0.0232, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 129.15it/s]

Log [0.0h, 0.0m, 0.901s]> Epoch [35/100] | loss: 0.0229, test loss: 0.0295, test acc: 0.8889 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 153.28it/s]

Log [0.0h, 0.0m, 0.768s]> Epoch [36/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 124.69it/s]

Log [0.0h, 0.0m, 0.940s]> Epoch [37/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 136.06it/s]

Log [0.0h, 0.0m, 0.856s]> Epoch [38/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 142.83it/s]

Log [0.0h, 0.0m, 0.818s]> Epoch [39/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 140.32it/s]

Log [0.0h, 0.0m, 0.840s]> Epoch [40/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 131.22it/s]

Log [0.0h, 0.0m, 0.893s]> Epoch [41/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 140.88it/s]

Log [0.0h, 0.0m, 0.828s]> Epoch [42/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 138.60it/s]

Log [0.0h, 0.0m, 0.840s]> Epoch [43/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 133.86it/s]

Log [0.0h, 0.0m, 0.875s]> Epoch [44/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 136.91it/s]

Log [0.0h, 0.0m, 0.870s]> Epoch [45/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125

100%|██████████| 112/112 [00:00<00:00, 135.92it/s]

Log [0.0h, 0.0m, 0.864s]> Epoch [46/100] | loss: 0.0228, test loss: 0.0295, test acc: 0.8889 | lr: 0.000125
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([10, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `e --> e`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
112 27
112 27

100%|██████████| 112/112 [00:00<00:00, 138.00it/s]

Log [0.0h, 0.0m, 0.855s]> Epoch [1/100] | loss: 0.0453, test loss: 0.0393, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 153.38it/s]

Log [0.0h, 0.0m, 0.763s]> Epoch [2/100] | loss: 0.0414, test loss: 0.0393, test acc: 0.8889 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 144.39it/s]

Log [0.0h, 0.0m, 0.814s]> Epoch [3/100] | loss: 0.0402, test loss: 0.0365, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 138.95it/s]

Log [0.0h, 0.0m, 0.839s]> Epoch [4/100] | loss: 0.0463, test loss: 0.0267, test acc: 0.9630 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 165.79it/s]

Log [0.0h, 0.0m, 0.712s]> Epoch [5/100] | loss: 0.0416, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 155.01it/s]

Log [0.0h, 0.0m, 0.754s]> Epoch [6/100] | loss: 0.0343, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 165.70it/s]

Log [0.0h, 0.0m, 0.712s]> Epoch [7/100] | loss: 0.0318, test loss: 0.0267, test acc: 0.9630 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 166.99it/s]

Log [0.0h, 0.0m, 0.704s]> Epoch [8/100] | loss: 0.0356, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 160.13it/s]

Log [0.0h, 0.0m, 0.734s]> Epoch [9/100] | loss: 0.0287, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 152.74it/s]

Log [0.0h, 0.0m, 0.772s]> Epoch [10/100] | loss: 0.0287, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 150.58it/s]

Log [0.0h, 0.0m, 0.780s]> Epoch [11/100] | loss: 0.0286, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 163.02it/s]

Log [0.0h, 0.0m, 0.720s]> Epoch [12/100] | loss: 0.0286, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 164.13it/s]

Log [0.0h, 0.0m, 0.714s]> Epoch [13/100] | loss: 0.0286, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 163.30it/s]

Log [0.0h, 0.0m, 0.727s]> Epoch [14/100] | loss: 0.0286, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 156.85it/s]

Log [0.0h, 0.0m, 0.748s]> Epoch [15/100] | loss: 0.0285, test loss: 0.0295, test acc: 0.9259 | lr: 0.001000

100%|██████████| 112/112 [00:00<00:00, 164.42it/s]

Log [0.0h, 0.0m, 0.713s]> Epoch [16/100] | loss: 0.0285, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 162.78it/s]

Log [0.0h, 0.0m, 0.725s]> Epoch [17/100] | loss: 0.0285, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 147.78it/s]

Log [0.0h, 0.0m, 0.796s]> Epoch [18/100] | loss: 0.0285, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 156.17it/s]

Log [0.0h, 0.0m, 0.749s]> Epoch [19/100] | loss: 0.0285, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 154.95it/s]

Log [0.0h, 0.0m, 0.755s]> Epoch [20/100] | loss: 0.0307, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 157.40it/s]

Log [0.0h, 0.0m, 0.745s]> Epoch [21/100] | loss: 0.0289, test loss: 0.0323, test acc: 0.8889 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 163.54it/s]

Log [0.0h, 0.0m, 0.716s]> Epoch [22/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 166.65it/s]

Log [0.0h, 0.0m, 0.710s]> Epoch [23/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 152.28it/s]

Log [0.0h, 0.0m, 0.769s]> Epoch [24/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 158.36it/s]

Log [0.0h, 0.0m, 0.745s]> Epoch [25/100] | loss: 0.0278, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 167.54it/s]

Log [0.0h, 0.0m, 0.700s]> Epoch [26/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000500

100%|██████████| 112/112 [00:00<00:00, 157.44it/s]

Log [0.0h, 0.0m, 0.743s]> Epoch [27/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 157.78it/s]

Log [0.0h, 0.0m, 0.747s]> Epoch [28/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 166.88it/s]

Log [0.0h, 0.0m, 0.702s]> Epoch [29/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 156.17it/s]

Log [0.0h, 0.0m, 0.750s]> Epoch [30/100] | loss: 0.0278, test loss: 0.0295, test acc: 0.9259 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 150.87it/s]

Log [0.0h, 0.0m, 0.781s]> Epoch [31/100] | loss: 0.0278, test loss: 0.0295, test acc: 0.9259 | lr: 0.000250

100%|██████████| 112/112 [00:00<00:00, 155.64it/s]

Log [0.0h, 0.0m, 0.751s]> Epoch [32/100] | loss: 0.0279, test loss: 0.0295, test acc: 0.9259 | lr: 0.000250
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([10, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `e --> e`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	eclipse dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>
108 31
108 31

100%|██████████| 108/108 [00:00<00:00, 154.44it/s]

Log [0.0h, 0.0m, 0.750s]> Epoch [1/100] | loss: 0.0417, test loss: 0.0551, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 152.38it/s]

Log [0.0h, 0.0m, 0.752s]> Epoch [2/100] | loss: 0.0400, test loss: 0.0551, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 165.13it/s]

Log [0.0h, 0.0m, 0.694s]> Epoch [3/100] | loss: 0.0377, test loss: 0.0551, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 164.90it/s]

Log [0.0h, 0.0m, 0.696s]> Epoch [4/100] | loss: 0.0351, test loss: 0.0576, test acc: 0.8387 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 163.23it/s]

Log [0.0h, 0.0m, 0.701s]> Epoch [5/100] | loss: 0.0342, test loss: 0.0576, test acc: 0.8387 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 157.60it/s]

Log [0.0h, 0.0m, 0.725s]> Epoch [6/100] | loss: 0.0349, test loss: 0.0369, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 157.56it/s]

Log [0.0h, 0.0m, 0.724s]> Epoch [7/100] | loss: 0.0328, test loss: 0.0430, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 161.28it/s]

Log [0.0h, 0.0m, 0.711s]> Epoch [8/100] | loss: 0.0312, test loss: 0.0454, test acc: 0.8387 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 163.26it/s]

Log [0.0h, 0.0m, 0.701s]> Epoch [9/100] | loss: 0.0311, test loss: 0.0430, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 153.75it/s]

Log [0.0h, 0.0m, 0.748s]> Epoch [10/100] | loss: 0.0309, test loss: 0.0430, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 154.55it/s]

Log [0.0h, 0.0m, 0.739s]> Epoch [11/100] | loss: 0.0310, test loss: 0.0344, test acc: 0.9032 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 162.97it/s]

Log [0.0h, 0.0m, 0.703s]> Epoch [12/100] | loss: 0.0320, test loss: 0.0551, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 153.53it/s]

Log [0.0h, 0.0m, 0.744s]> Epoch [13/100] | loss: 0.0314, test loss: 0.0320, test acc: 0.9355 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 146.12it/s]

Log [0.0h, 0.0m, 0.780s]> Epoch [14/100] | loss: 0.0330, test loss: 0.0491, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 152.71it/s]

Log [0.0h, 0.0m, 0.756s]> Epoch [15/100] | loss: 0.0326, test loss: 0.0576, test acc: 0.8387 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 150.13it/s]

Log [0.0h, 0.0m, 0.759s]> Epoch [16/100] | loss: 0.0319, test loss: 0.0576, test acc: 0.8387 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 155.17it/s]

Log [0.0h, 0.0m, 0.745s]> Epoch [17/100] | loss: 0.0320, test loss: 0.0551, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 154.87it/s]

Log [0.0h, 0.0m, 0.748s]> Epoch [18/100] | loss: 0.0367, test loss: 0.0551, test acc: 0.8710 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 156.96it/s]

Log [0.0h, 0.0m, 0.729s]> Epoch [19/100] | loss: 0.0315, test loss: 0.0576, test acc: 0.8387 | lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 158.09it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.722s]> Epoch [20/100] | loss: 0.0317, test loss: 0.0515, test acc: 0.8387 | lr: 0.001000
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([10, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `o --> o`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing
Log [0.0h, 0.0m, 0.000s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.003s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Osgeo>

100%|██████████| 24/24 [00:00<00:00, 14016.05it/s]
100%|██████████| 24/24 [00:00<00:00, 37800.71it/s]

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `o --> o`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
16 4
16 4

100%|██████████| 16/16 [00:00<00:00, 26.34it/s]

Log [0.0h, 0.0m, 0.637s]> Epoch [1/100] | loss: 0.1070, test loss: 0.0962, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.45it/s]

Log [0.0h, 0.0m, 0.631s]> Epoch [2/100] | loss: 0.0746, test loss: 0.0866, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.87it/s]

Log [0.0h, 0.0m, 0.602s]> Epoch [3/100] | loss: 0.0597, test loss: 0.1151, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.32it/s]

Log [0.0h, 0.0m, 0.616s]> Epoch [4/100] | loss: 0.0601, test loss: 0.0962, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.36it/s]

Log [0.0h, 0.0m, 0.616s]> Epoch [5/100] | loss: 0.0459, test loss: 0.0962, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.33it/s]

Log [0.0h, 0.0m, 0.635s]> Epoch [6/100] | loss: 0.0450, test loss: 0.0962, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.80it/s]

Log [0.0h, 0.0m, 0.627s]> Epoch [7/100] | loss: 0.0916, test loss: 0.0962, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 29.27it/s]

Log [0.0h, 0.0m, 0.573s]> Epoch [8/100] | loss: 0.0860, test loss: 0.0962, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.58it/s]

Log [0.0h, 0.0m, 0.610s]> Epoch [9/100] | loss: 0.0472, test loss: 0.1339, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.21it/s]

Log [0.0h, 0.0m, 0.618s]> Epoch [10/100] | loss: 0.0453, test loss: 0.1339, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.24it/s]

Log [0.0h, 0.0m, 0.645s]> Epoch [11/100] | loss: 0.0451, test loss: 0.1339, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.57it/s]

Log [0.0h, 0.0m, 0.609s]> Epoch [12/100] | loss: 0.0448, test loss: 0.1151, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.80it/s]

Log [0.0h, 0.0m, 0.589s]> Epoch [13/100] | loss: 0.0448, test loss: 0.1151, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 25.98it/s]

Log [0.0h, 0.0m, 0.642s]> Epoch [14/100] | loss: 0.0446, test loss: 0.1151, test acc: 0.5000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 29.73it/s]

Log [0.0h, 0.0m, 0.571s]> Epoch [15/100] | loss: 0.0447, test loss: 0.0962, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.20it/s]

Log [0.0h, 0.0m, 0.648s]> Epoch [16/100] | loss: 0.0453, test loss: 0.0962, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.36it/s]

Log [0.0h, 0.0m, 0.633s]> Epoch [17/100] | loss: 0.0399, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.29it/s]

Log [0.0h, 0.0m, 0.593s]> Epoch [18/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.17it/s]

Log [0.0h, 0.0m, 0.600s]> Epoch [19/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.64it/s]

Log [0.0h, 0.0m, 0.632s]> Epoch [20/100] | loss: 0.0446, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.04it/s]

Log [0.0h, 0.0m, 0.599s]> Epoch [21/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.27it/s]

Log [0.0h, 0.0m, 0.597s]> Epoch [22/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.60it/s]

Log [0.0h, 0.0m, 0.586s]> Epoch [23/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.17it/s]

Log [0.0h, 0.0m, 0.594s]> Epoch [24/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.60it/s]

Log [0.0h, 0.0m, 0.587s]> Epoch [25/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 26.89it/s]

Log [0.0h, 0.0m, 0.624s]> Epoch [26/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 25.63it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/perfdata.py:713: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data = pd.concat([self.data, new_entries], ignore_index=True)

Log [0.0h, 0.0m, 0.653s]> Epoch [27/100] | loss: 0.0445, test loss: 0.1339, test acc: 0.2500 | lr: 0.000250
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([21, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `o --> o`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
16 4
16 4

100%|██████████| 16/16 [00:00<00:00, 26.11it/s]

Log [0.0h, 0.0m, 0.636s]> Epoch [1/100] | loss: 0.1123, test loss: 0.0866, test acc: 0.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.29it/s]

Log [0.0h, 0.0m, 0.628s]> Epoch [2/100] | loss: 0.0828, test loss: 0.0866, test acc: 0.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 25.74it/s]

Log [0.0h, 0.0m, 0.641s]> Epoch [3/100] | loss: 0.0765, test loss: 0.0866, test acc: 0.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.51it/s]

Log [0.0h, 0.0m, 0.611s]> Epoch [4/100] | loss: 0.0565, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 24.93it/s]

Log [0.0h, 0.0m, 0.663s]> Epoch [5/100] | loss: 0.0552, test loss: 0.0678, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 25.90it/s]

Log [0.0h, 0.0m, 0.638s]> Epoch [6/100] | loss: 0.0517, test loss: 0.0113, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.16it/s]

Log [0.0h, 0.0m, 0.610s]> Epoch [7/100] | loss: 0.0601, test loss: 0.0866, test acc: 0.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.86it/s]

Log [0.0h, 0.0m, 0.615s]> Epoch [8/100] | loss: 0.0463, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.47it/s]

Log [0.0h, 0.0m, 0.603s]> Epoch [9/100] | loss: 0.0447, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.77it/s]

Log [0.0h, 0.0m, 0.618s]> Epoch [10/100] | loss: 0.0447, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.48it/s]

Log [0.0h, 0.0m, 0.623s]> Epoch [11/100] | loss: 0.0445, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.49it/s]

Log [0.0h, 0.0m, 0.627s]> Epoch [12/100] | loss: 0.0445, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 25.46it/s]

Log [0.0h, 0.0m, 0.647s]> Epoch [13/100] | loss: 0.0445, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.61it/s]

Log [0.0h, 0.0m, 0.622s]> Epoch [14/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.60it/s]

Log [0.0h, 0.0m, 0.621s]> Epoch [15/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.63it/s]

Log [0.0h, 0.0m, 0.620s]> Epoch [16/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.59it/s]

Log [0.0h, 0.0m, 0.629s]> Epoch [17/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 24.81it/s]

Log [0.0h, 0.0m, 0.667s]> Epoch [18/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.33it/s]

Log [0.0h, 0.0m, 0.627s]> Epoch [19/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 27.71it/s]

Log [0.0h, 0.0m, 0.596s]> Epoch [20/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.15it/s]

Log [0.0h, 0.0m, 0.657s]> Epoch [21/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.00it/s]

Log [0.0h, 0.0m, 0.639s]> Epoch [22/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.40it/s]

Log [0.0h, 0.0m, 0.652s]> Epoch [23/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.65it/s]

Log [0.0h, 0.0m, 0.643s]> Epoch [24/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 27.29it/s]

Log [0.0h, 0.0m, 0.605s]> Epoch [25/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 24.97it/s]

Log [0.0h, 0.0m, 0.663s]> Epoch [26/100] | loss: 0.0444, test loss: 0.0302, test acc: 0.7500 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([123, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `o --> o`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
16 4
16 4

100%|██████████| 16/16 [00:00<00:00, 35.67it/s]

Log [0.0h, 0.0m, 0.507s]> Epoch [1/100] | loss: 0.0911, test loss: 0.2660, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 37.46it/s]

Log [0.0h, 0.0m, 0.478s]> Epoch [2/100] | loss: 0.0737, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 33.05it/s]

Log [0.0h, 0.0m, 0.534s]> Epoch [3/100] | loss: 0.0706, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 31.96it/s]

Log [0.0h, 0.0m, 0.551s]> Epoch [4/100] | loss: 0.0610, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 33.04it/s]

Log [0.0h, 0.0m, 0.534s]> Epoch [5/100] | loss: 0.0469, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 35.71it/s]

Log [0.0h, 0.0m, 0.505s]> Epoch [6/100] | loss: 0.0361, test loss: 0.1339, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 38.47it/s]

Log [0.0h, 0.0m, 0.476s]> Epoch [7/100] | loss: 0.0357, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 39.31it/s]

Log [0.0h, 0.0m, 0.458s]> Epoch [8/100] | loss: 0.0307, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 35.71it/s]

Log [0.0h, 0.0m, 0.499s]> Epoch [9/100] | loss: 0.0477, test loss: 0.2000, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 38.35it/s]

Log [0.0h, 0.0m, 0.468s]> Epoch [10/100] | loss: 0.0792, test loss: 0.2000, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 38.64it/s]

Log [0.0h, 0.0m, 0.471s]> Epoch [11/100] | loss: 0.0393, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 36.63it/s]

Log [0.0h, 0.0m, 0.487s]> Epoch [12/100] | loss: 0.0369, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 35.69it/s]

Log [0.0h, 0.0m, 0.505s]> Epoch [13/100] | loss: 0.0454, test loss: 0.1339, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 33.18it/s]

Log [0.0h, 0.0m, 0.539s]> Epoch [14/100] | loss: 0.0347, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 35.68it/s]

Log [0.0h, 0.0m, 0.498s]> Epoch [15/100] | loss: 0.0305, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 35.04it/s]

Log [0.0h, 0.0m, 0.515s]> Epoch [16/100] | loss: 0.0304, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.19it/s]

Log [0.0h, 0.0m, 0.634s]> Epoch [17/100] | loss: 0.0305, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.11it/s]

Log [0.0h, 0.0m, 0.632s]> Epoch [18/100] | loss: 0.0304, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 30.82it/s]

Log [0.0h, 0.0m, 0.575s]> Epoch [19/100] | loss: 0.0304, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 29.77it/s]

Log [0.0h, 0.0m, 0.598s]> Epoch [20/100] | loss: 0.0304, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 35.87it/s]

Log [0.0h, 0.0m, 0.497s]> Epoch [21/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 37.30it/s]

Log [0.0h, 0.0m, 0.480s]> Epoch [22/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 36.75it/s]

Log [0.0h, 0.0m, 0.487s]> Epoch [23/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 38.49it/s]

Log [0.0h, 0.0m, 0.469s]> Epoch [24/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 38.17it/s]

Log [0.0h, 0.0m, 0.470s]> Epoch [25/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 36.15it/s]

Log [0.0h, 0.0m, 0.493s]> Epoch [26/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 34.25it/s]

Log [0.0h, 0.0m, 0.519s]> Epoch [27/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 33.48it/s]

Log [0.0h, 0.0m, 0.527s]> Epoch [28/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 37.11it/s]

Log [0.0h, 0.0m, 0.493s]> Epoch [29/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 34.53it/s]

Log [0.0h, 0.0m, 0.536s]> Epoch [30/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 33.66it/s]

Log [0.0h, 0.0m, 0.530s]> Epoch [31/100] | loss: 0.0303, test loss: 0.0678, test acc: 1.0000 | lr: 0.000250
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([123, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `o --> o`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
16 4
16 4

100%|██████████| 16/16 [00:00<00:00, 29.47it/s]

Log [0.0h, 0.0m, 0.572s]> Epoch [1/100] | loss: 0.1093, test loss: 0.0866, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.42it/s]

Log [0.0h, 0.0m, 0.595s]> Epoch [2/100] | loss: 0.0809, test loss: 0.0866, test acc: 0.2500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.92it/s]

Log [0.0h, 0.0m, 0.605s]> Epoch [3/100] | loss: 0.0755, test loss: 0.0678, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.16it/s]

Log [0.0h, 0.0m, 0.633s]> Epoch [4/100] | loss: 0.0551, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.34it/s]

Log [0.0h, 0.0m, 0.597s]> Epoch [5/100] | loss: 0.0473, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.78it/s]

Log [0.0h, 0.0m, 0.625s]> Epoch [6/100] | loss: 0.0452, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 29.08it/s]

Log [0.0h, 0.0m, 0.582s]> Epoch [7/100] | loss: 0.0448, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.42it/s]

Log [0.0h, 0.0m, 0.611s]> Epoch [8/100] | loss: 0.0447, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 29.18it/s]

Log [0.0h, 0.0m, 0.580s]> Epoch [9/100] | loss: 0.0446, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.72it/s]

Log [0.0h, 0.0m, 0.585s]> Epoch [10/100] | loss: 0.0447, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 29.14it/s]

Log [0.0h, 0.0m, 0.591s]> Epoch [11/100] | loss: 0.0445, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.54it/s]

Log [0.0h, 0.0m, 0.614s]> Epoch [12/100] | loss: 0.0445, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.65it/s]

Log [0.0h, 0.0m, 0.600s]> Epoch [13/100] | loss: 0.0445, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 24.56it/s]

Log [0.0h, 0.0m, 0.679s]> Epoch [14/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.49it/s]

Log [0.0h, 0.0m, 0.608s]> Epoch [15/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.79it/s]

Log [0.0h, 0.0m, 0.607s]> Epoch [16/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.71it/s]

Log [0.0h, 0.0m, 0.666s]> Epoch [17/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.49it/s]

Log [0.0h, 0.0m, 0.660s]> Epoch [18/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.75it/s]

Log [0.0h, 0.0m, 0.626s]> Epoch [19/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.87it/s]

Log [0.0h, 0.0m, 0.650s]> Epoch [20/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 27.03it/s]

Log [0.0h, 0.0m, 0.634s]> Epoch [21/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.61it/s]

Log [0.0h, 0.0m, 0.627s]> Epoch [22/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.77it/s]

Log [0.0h, 0.0m, 0.649s]> Epoch [23/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.79it/s]

Log [0.0h, 0.0m, 0.651s]> Epoch [24/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.54it/s]

Log [0.0h, 0.0m, 0.630s]> Epoch [25/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 27.44it/s]

Log [0.0h, 0.0m, 0.626s]> Epoch [26/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 27.34it/s]

Log [0.0h, 0.0m, 0.613s]> Epoch [27/100] | loss: 0.0443, test loss: 0.0490, test acc: 0.7500 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 27.96it/s]

Log [0.0h, 0.0m, 0.603s]> Epoch [28/100] | loss: 0.0444, test loss: 0.0490, test acc: 0.7500 | lr: 0.000250
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([123, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `o --> o`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	osgeo dataset, version tech: 2, social: 2 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
16 4
16 4

100%|██████████| 16/16 [00:00<00:00, 25.44it/s]

Log [0.0h, 0.0m, 0.660s]> Epoch [1/100] | loss: 0.0949, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.64it/s]

Log [0.0h, 0.0m, 0.623s]> Epoch [2/100] | loss: 0.0737, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.43it/s]

Log [0.0h, 0.0m, 0.584s]> Epoch [3/100] | loss: 0.0624, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.81it/s]

Log [0.0h, 0.0m, 0.576s]> Epoch [4/100] | loss: 0.0520, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.78it/s]

Log [0.0h, 0.0m, 0.622s]> Epoch [5/100] | loss: 0.0365, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.42it/s]

Log [0.0h, 0.0m, 0.627s]> Epoch [6/100] | loss: 0.0355, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.96it/s]

Log [0.0h, 0.0m, 0.597s]> Epoch [7/100] | loss: 0.0353, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.17it/s]

Log [0.0h, 0.0m, 0.633s]> Epoch [8/100] | loss: 0.0352, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 24.73it/s]

Log [0.0h, 0.0m, 0.669s]> Epoch [9/100] | loss: 0.0352, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 24.49it/s]

Log [0.0h, 0.0m, 0.674s]> Epoch [10/100] | loss: 0.0351, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 25.27it/s]

Log [0.0h, 0.0m, 0.654s]> Epoch [11/100] | loss: 0.0351, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.02it/s]

Log [0.0h, 0.0m, 0.636s]> Epoch [12/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 24.79it/s]

Log [0.0h, 0.0m, 0.665s]> Epoch [13/100] | loss: 0.0351, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 25.89it/s]

Log [0.0h, 0.0m, 0.645s]> Epoch [14/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.62it/s]

Log [0.0h, 0.0m, 0.625s]> Epoch [15/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.10it/s]

Log [0.0h, 0.0m, 0.634s]> Epoch [16/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 27.03it/s]

Log [0.0h, 0.0m, 0.616s]> Epoch [17/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 24.69it/s]

Log [0.0h, 0.0m, 0.674s]> Epoch [18/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 23.89it/s]

Log [0.0h, 0.0m, 0.696s]> Epoch [19/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.24it/s]

Log [0.0h, 0.0m, 0.660s]> Epoch [20/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.65it/s]

Log [0.0h, 0.0m, 0.648s]> Epoch [21/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.37it/s]

Log [0.0h, 0.0m, 0.653s]> Epoch [22/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 26.48it/s]

Log [0.0h, 0.0m, 0.624s]> Epoch [23/100] | loss: 0.0349, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 25.68it/s]

Log [0.0h, 0.0m, 0.643s]> Epoch [24/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 27.38it/s]

Log [0.0h, 0.0m, 0.604s]> Epoch [25/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 28.00it/s]

Log [0.0h, 0.0m, 0.591s]> Epoch [26/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 27.29it/s]

Log [0.0h, 0.0m, 0.607s]> Epoch [27/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000250

100%|██████████| 16/16 [00:00<00:00, 27.59it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.600s]> Epoch [28/100] | loss: 0.0350, test loss: 0.0490, test acc: 1.0000 | lr: 0.000250
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([123, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `g --> g`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 100.00% of the data reserved for testing
Log [0.0h, 0.0m, 0.000s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.004s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Github>

100%|██████████| 21/21 [00:00<00:00, 8511.83it/s]
100%|██████████| 21/21 [00:00<00:00, 9890.00it/s]

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `g --> g`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
17 4
17 4

100%|██████████| 17/17 [00:01<00:00, 15.52it/s]

Log [0.0h, 0.0m, 1.161s]> Epoch [1/100] | loss: 0.0952, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.37it/s]

Log [0.0h, 0.0m, 1.163s]> Epoch [2/100] | loss: 0.0870, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:00<00:00, 17.05it/s]

Log [0.0h, 0.0m, 1.053s]> Epoch [3/100] | loss: 0.0868, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.58it/s]

Log [0.0h, 0.0m, 1.084s]> Epoch [4/100] | loss: 0.0868, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.54it/s]

Log [0.0h, 0.0m, 1.086s]> Epoch [5/100] | loss: 0.0867, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.96it/s]

Log [0.0h, 0.0m, 1.133s]> Epoch [6/100] | loss: 0.0862, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.48it/s]

Log [0.0h, 0.0m, 1.156s]> Epoch [7/100] | loss: 0.0969, test loss: 0.0866, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.69it/s]

Log [0.0h, 0.0m, 1.154s]> Epoch [8/100] | loss: 0.0859, test loss: 0.0678, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.17it/s]

Log [0.0h, 0.0m, 1.110s]> Epoch [9/100] | loss: 0.0785, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.68it/s]

Log [0.0h, 0.0m, 1.076s]> Epoch [10/100] | loss: 0.0780, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.76it/s]

Log [0.0h, 0.0m, 1.155s]> Epoch [11/100] | loss: 0.0780, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.19it/s]

Log [0.0h, 0.0m, 1.181s]> Epoch [12/100] | loss: 0.0779, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.54it/s]

Log [0.0h, 0.0m, 1.170s]> Epoch [13/100] | loss: 0.0779, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.56it/s]

Log [0.0h, 0.0m, 1.238s]> Epoch [14/100] | loss: 0.0779, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.77it/s]

Log [0.0h, 0.0m, 1.206s]> Epoch [15/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.39it/s]

Log [0.0h, 0.0m, 1.169s]> Epoch [16/100] | loss: 0.0779, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.02it/s]

Log [0.0h, 0.0m, 1.190s]> Epoch [17/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.23it/s]

Log [0.0h, 0.0m, 1.174s]> Epoch [18/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.65it/s]

Log [0.0h, 0.0m, 1.143s]> Epoch [19/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.51it/s]

Log [0.0h, 0.0m, 1.154s]> Epoch [20/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.93it/s]

Log [0.0h, 0.0m, 1.209s]> Epoch [21/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.55it/s]

Log [0.0h, 0.0m, 1.156s]> Epoch [22/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.11it/s]

Log [0.0h, 0.0m, 1.181s]> Epoch [23/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.09it/s]

Log [0.0h, 0.0m, 1.113s]> Epoch [24/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.87it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/perfdata.py:713: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.data = pd.concat([self.data, new_entries], ignore_index=True)

Log [0.0h, 0.0m, 1.133s]> Epoch [25/100] | loss: 0.0778, test loss: 0.0490, test acc: 1.0000 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([73, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `g --> g`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
17 4
17 4

100%|██████████| 17/17 [00:01<00:00, 15.99it/s]

Log [0.0h, 0.0m, 1.110s]> Epoch [1/100] | loss: 0.0923, test loss: 0.0866, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.75it/s]

Log [0.0h, 0.0m, 1.129s]> Epoch [2/100] | loss: 0.0826, test loss: 0.1527, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.74it/s]

Log [0.0h, 0.0m, 1.206s]> Epoch [3/100] | loss: 0.0796, test loss: 0.0866, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.41it/s]

Log [0.0h, 0.0m, 1.147s]> Epoch [4/100] | loss: 0.0699, test loss: 0.1527, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.95it/s]

Log [0.0h, 0.0m, 1.111s]> Epoch [5/100] | loss: 0.0688, test loss: 0.2188, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.62it/s]

Log [0.0h, 0.0m, 1.150s]> Epoch [6/100] | loss: 0.0710, test loss: 0.0866, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.64it/s]

Log [0.0h, 0.0m, 1.137s]> Epoch [7/100] | loss: 0.0687, test loss: 0.1527, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.92it/s]

Log [0.0h, 0.0m, 1.185s]> Epoch [8/100] | loss: 0.0649, test loss: 0.2188, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.28it/s]

Log [0.0h, 0.0m, 1.164s]> Epoch [9/100] | loss: 0.0647, test loss: 0.2188, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.50it/s]

Log [0.0h, 0.0m, 1.216s]> Epoch [10/100] | loss: 0.0647, test loss: 0.2188, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.52it/s]

Log [0.0h, 0.0m, 1.138s]> Epoch [11/100] | loss: 0.0647, test loss: 0.2188, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.77it/s]

Log [0.0h, 0.0m, 1.195s]> Epoch [12/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.08it/s]

Log [0.0h, 0.0m, 1.101s]> Epoch [13/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.44it/s]

Log [0.0h, 0.0m, 1.145s]> Epoch [14/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.75it/s]

Log [0.0h, 0.0m, 1.122s]> Epoch [15/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.53it/s]

Log [0.0h, 0.0m, 1.141s]> Epoch [16/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.04it/s]

Log [0.0h, 0.0m, 1.191s]> Epoch [17/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.21it/s]

Log [0.0h, 0.0m, 1.161s]> Epoch [18/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.93it/s]

Log [0.0h, 0.0m, 1.183s]> Epoch [19/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.76it/s]

Log [0.0h, 0.0m, 1.196s]> Epoch [20/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.90it/s]

Log [0.0h, 0.0m, 1.190s]> Epoch [21/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.65it/s]

Log [0.0h, 0.0m, 1.210s]> Epoch [22/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.77it/s]

Log [0.0h, 0.0m, 1.198s]> Epoch [23/100] | loss: 0.0646, test loss: 0.2188, test acc: 0.5000 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([103, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `g --> g`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
17 4
17 4

100%|██████████| 17/17 [00:01<00:00, 14.73it/s]

Log [0.0h, 0.0m, 1.196s]> Epoch [1/100] | loss: 0.1075, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.50it/s]

Log [0.0h, 0.0m, 1.214s]> Epoch [2/100] | loss: 0.0885, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.82it/s]

Log [0.0h, 0.0m, 1.192s]> Epoch [3/100] | loss: 0.0873, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.58it/s]

Log [0.0h, 0.0m, 1.205s]> Epoch [4/100] | loss: 0.0871, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.18it/s]

Log [0.0h, 0.0m, 1.244s]> Epoch [5/100] | loss: 0.0871, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.14it/s]

Log [0.0h, 0.0m, 1.158s]> Epoch [6/100] | loss: 0.0869, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 13.96it/s]

Log [0.0h, 0.0m, 1.256s]> Epoch [7/100] | loss: 0.0869, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.40it/s]

Log [0.0h, 0.0m, 1.223s]> Epoch [8/100] | loss: 0.0866, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.21it/s]

Log [0.0h, 0.0m, 1.235s]> Epoch [9/100] | loss: 0.0991, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.47it/s]

Log [0.0h, 0.0m, 1.218s]> Epoch [10/100] | loss: 0.0783, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.31it/s]

Log [0.0h, 0.0m, 1.226s]> Epoch [11/100] | loss: 0.0797, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.19it/s]

Log [0.0h, 0.0m, 1.242s]> Epoch [12/100] | loss: 0.0744, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.90it/s]

Log [0.0h, 0.0m, 1.180s]> Epoch [13/100] | loss: 0.0744, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.84it/s]

Log [0.0h, 0.0m, 1.183s]> Epoch [14/100] | loss: 0.0735, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.09it/s]

Log [0.0h, 0.0m, 1.174s]> Epoch [15/100] | loss: 0.0735, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.25it/s]

Log [0.0h, 0.0m, 1.230s]> Epoch [16/100] | loss: 0.0735, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.17it/s]

Log [0.0h, 0.0m, 1.162s]> Epoch [17/100] | loss: 0.0735, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.69it/s]

Log [0.0h, 0.0m, 1.195s]> Epoch [18/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.51it/s]

Log [0.0h, 0.0m, 1.132s]> Epoch [19/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.11it/s]

Log [0.0h, 0.0m, 1.248s]> Epoch [20/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.94it/s]

Log [0.0h, 0.0m, 1.175s]> Epoch [21/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.17it/s]

Log [0.0h, 0.0m, 1.158s]> Epoch [22/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.06it/s]

Log [0.0h, 0.0m, 1.257s]> Epoch [23/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 13.23it/s]

Log [0.0h, 0.0m, 1.322s]> Epoch [24/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.40it/s]

Log [0.0h, 0.0m, 1.239s]> Epoch [25/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.17it/s]

Log [0.0h, 0.0m, 1.251s]> Epoch [26/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.82it/s]

Log [0.0h, 0.0m, 1.205s]> Epoch [27/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.85it/s]

Log [0.0h, 0.0m, 1.181s]> Epoch [28/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.58it/s]

Log [0.0h, 0.0m, 1.202s]> Epoch [29/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.92it/s]

Log [0.0h, 0.0m, 1.182s]> Epoch [30/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 14.30it/s]

Log [0.0h, 0.0m, 1.228s]> Epoch [31/100] | loss: 0.0734, test loss: 0.0678, test acc: 1.0000 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([103, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `g --> g`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
17 4
17 4

100%|██████████| 17/17 [00:01<00:00, 16.75it/s]

Log [0.0h, 0.0m, 1.080s]> Epoch [1/100] | loss: 0.0941, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:00<00:00, 17.54it/s]

Log [0.0h, 0.0m, 1.034s]> Epoch [2/100] | loss: 0.0868, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:00<00:00, 17.59it/s]

Log [0.0h, 0.0m, 1.036s]> Epoch [3/100] | loss: 0.0817, test loss: 0.1339, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.84it/s]

Log [0.0h, 0.0m, 1.154s]> Epoch [4/100] | loss: 0.0764, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.59it/s]

Log [0.0h, 0.0m, 1.096s]> Epoch [5/100] | loss: 0.0738, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.30it/s]

Log [0.0h, 0.0m, 1.112s]> Epoch [6/100] | loss: 0.0737, test loss: 0.1339, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.30it/s]

Log [0.0h, 0.0m, 1.183s]> Epoch [7/100] | loss: 0.0736, test loss: 0.1339, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.76it/s]

Log [0.0h, 0.0m, 1.086s]> Epoch [8/100] | loss: 0.0735, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 14.28it/s]

Log [0.0h, 0.0m, 1.254s]> Epoch [9/100] | loss: 0.0735, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:00<00:00, 18.01it/s]

Log [0.0h, 0.0m, 1.007s]> Epoch [10/100] | loss: 0.0735, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.10it/s]

Log [0.0h, 0.0m, 1.187s]> Epoch [11/100] | loss: 0.0735, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 15.54it/s]

Log [0.0h, 0.0m, 1.155s]> Epoch [12/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.001000

100%|██████████| 17/17 [00:01<00:00, 16.49it/s]

Log [0.0h, 0.0m, 1.093s]> Epoch [13/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.65it/s]

Log [0.0h, 0.0m, 1.086s]> Epoch [14/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.05it/s]

Log [0.0h, 0.0m, 1.121s]> Epoch [15/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.36it/s]

Log [0.0h, 0.0m, 1.101s]> Epoch [16/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.06it/s]

Log [0.0h, 0.0m, 1.145s]> Epoch [17/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:00<00:00, 17.22it/s]

Log [0.0h, 0.0m, 1.050s]> Epoch [18/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.28it/s]

Log [0.0h, 0.0m, 1.115s]> Epoch [19/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 15.86it/s]

Log [0.0h, 0.0m, 1.133s]> Epoch [20/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.23it/s]

Log [0.0h, 0.0m, 1.109s]> Epoch [21/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.19it/s]

Log [0.0h, 0.0m, 1.111s]> Epoch [22/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.17it/s]

Log [0.0h, 0.0m, 1.113s]> Epoch [23/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000500

100%|██████████| 17/17 [00:01<00:00, 16.65it/s]

Log [0.0h, 0.0m, 1.083s]> Epoch [24/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000250

100%|██████████| 17/17 [00:00<00:00, 17.36it/s]

Log [0.0h, 0.0m, 1.041s]> Epoch [25/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000250

100%|██████████| 17/17 [00:00<00:00, 17.74it/s]

Log [0.0h, 0.0m, 1.022s]> Epoch [26/100] | loss: 0.0734, test loss: 0.0866, test acc: 0.7500 | lr: 0.000250
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([103, 14])

<Decoded Transfer Strategy>
Log [0.0h, 0.0m, 0.000s]> Original: `g --> g`
Options selected for train set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 0.00% of the data reserved for training
Options selected for test set:
Log [0.0h, 0.0m, 0.000s]> 	github dataset, version tech: 3, social: 4 with no augmentations using 100.00% of the data reserved for testing

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>
16 5
16 5

100%|██████████| 16/16 [00:00<00:00, 16.92it/s]

Log [0.0h, 0.0m, 1.020s]> Epoch [1/100] | loss: 0.1099, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 16.02it/s]

Log [0.0h, 0.0m, 1.067s]> Epoch [2/100] | loss: 0.0863, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 16.41it/s]

Log [0.0h, 0.0m, 1.053s]> Epoch [3/100] | loss: 0.0771, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.11it/s]

Log [0.0h, 0.0m, 1.003s]> Epoch [4/100] | loss: 0.0687, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 16.94it/s]

Log [0.0h, 0.0m, 1.014s]> Epoch [5/100] | loss: 0.0684, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.26it/s]

Log [0.0h, 0.0m, 0.996s]> Epoch [6/100] | loss: 0.0682, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 16.60it/s]

Log [0.0h, 0.0m, 1.031s]> Epoch [7/100] | loss: 0.0681, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:01<00:00, 15.46it/s]

Log [0.0h, 0.0m, 1.102s]> Epoch [8/100] | loss: 0.0681, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 16.50it/s]

Log [0.0h, 0.0m, 1.045s]> Epoch [9/100] | loss: 0.0680, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:01<00:00, 15.81it/s]

Log [0.0h, 0.0m, 1.091s]> Epoch [10/100] | loss: 0.0680, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 16.00it/s]

Log [0.0h, 0.0m, 1.069s]> Epoch [11/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:01<00:00, 14.79it/s]

Log [0.0h, 0.0m, 1.183s]> Epoch [12/100] | loss: 0.0680, test loss: 0.0866, test acc: 0.8000 | lr: 0.001000

100%|██████████| 16/16 [00:01<00:00, 15.29it/s]

Log [0.0h, 0.0m, 1.113s]> Epoch [13/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 17.49it/s]

Log [0.0h, 0.0m, 0.982s]> Epoch [14/100] | loss: 0.0680, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 17.37it/s]

Log [0.0h, 0.0m, 0.989s]> Epoch [15/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 16.91it/s]

Log [0.0h, 0.0m, 1.015s]> Epoch [16/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 16.00it/s]

Log [0.0h, 0.0m, 1.084s]> Epoch [17/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:01<00:00, 15.62it/s]

Log [0.0h, 0.0m, 1.110s]> Epoch [18/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:01<00:00, 14.20it/s]

Log [0.0h, 0.0m, 1.212s]> Epoch [19/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:01<00:00, 15.86it/s]

Log [0.0h, 0.0m, 1.077s]> Epoch [20/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500

100%|██████████| 16/16 [00:00<00:00, 16.14it/s]

Log [0.0h, 0.0m, 1.068s]> Epoch [21/100] | loss: 0.0679, test loss: 0.0866, test acc: 0.8000 | lr: 0.000500
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([103, 14])

In [5]:
median_folds = {
    inc: (set(f[0]), set(f[1]))
    for inc, f in median_folds.items()
}

In [6]:
from json import dumps
print(list(map(len, median_folds["apache"])))
print(list(map(len, median_folds["eclipse"])))
print(list(map(len, median_folds["osgeo"])))
print(list(map(len, median_folds["github"])))

[211, 52]
[108, 31]
[16, 4]
[16, 5]

In [7]:
print(median_folds)

{'apache': ({'skywalking', 'dubbo', 'opennlp', 'photark', 'ibatis', 'mesos', 'batchee', 'hise', 'daffodil', 'manifoldcf', 'carbondata', 'curator', 'shindig', 'samoa', 'mod_ftp', 'droids', 'rocketmq', 'zeta', 'fineract', 'trafficserver', 'cloudstack', 'airflow', 'parquet', 'lucy', 'xap', 'mrql', 'trafodion', 'directmemory', 'pulsar', 'ripple', 'jdo', 'tamaya', 'edgent', 'nuvem', 'guacamole', 'stonehenge', 'devicemap', 'roller', 'directory', 'nmaven', 'weex', 'plc4x', 'superset', 'iota', 'derby', 'bigtop', 'rya', 'storm', 'ctakes', 'ratis', 'openjpa', 'jackrabbit', 'druid', 'crunch', 'concerted', 'myriad', 'commonsrdf', 'lens', 'struts', 'thrift', 'click', 'etch', 'empire', 'imperius', 'sentry', 'flex', 'airavata', 'stratos', 'apex', 'npanday', 'lokahi', 'marmotta', 'solr', 'servicecomb', 'vxquery', 'metamodel', 'bval', 'esme', 'oozie', 'any23', 'wicket', 'subversion', 'aries', 'openwebbeans', 'clerezza', 'juneau', 'pig', 'tephra', 'singa', 'pubscribe', 'sqoop', 'pivot', 'sling', 'lucenenet', 'iceberg', 'triplesoup', 'buildr', 'olingo', 'ivy', 'jclouds', 'openwhisk', 'openaz', 'cmda', 'bluesky', 'gearpump', 'htrace', 'chukwa', 'warble', 'samza', 'composer', 'pinot', 'datasketches', 'helix', 'felix', 'sanselan', 'cassandra', 'agila', 'ignite', 'ofbiz', 'giraph', 'synapse', 'groovy', 'drill', 'datafu', 'activemq', 'corinthia', 'heraldry', 'wookie', 'myfaces', 'systemml', 'tashi', 'hama', 'pirk', 'odf', 'kitty', 'nifi', 'harmony', 'shiro', 'iotdb', 'allura', 'sis', 'oltu', 'shardingsphere', 'omid', 'twill', 'ace', 'uima', 'beam', 'onami', 'openoffice', 'metron', 'tuscany', 'horn', 'celix', 'sirona', 'stanbol', 'mynewt', 'wave', 'cordova', 'quickstep', 'mnemonic', 'abdera', 'netbeans', 'openmeetings', 'kato', 'cxf', 'atlas', 'kafka', 'commons', 'usergrid', 'hdt', 'griffin', 'aurora', 'vcl', 'hudi', 'yoko', 'fluo', 'bloodhound', 'kudu', 'stdcxx', 'zeppelin', 'muse', 'couchdb', 'bookkeeper', 'ant', 'slider', 'streams', 'jspwiki', 'ariatosca', 'tika', 'gora', 'kalumet', 'apisix', 'tez', 'syncope', 'whirr', 'climate', 'taverna', 'impala', 'ranger', 'deltaspike', 's4', 'adffaces', 'ambari', 'spark', 'johnzon', 'chemistry', 'flink', 'wink', 'kylin', 'jena'}, {'trafficcontrol', 'cayenne', 'freemarker', 'tinkerpop', 'tajo', 'echarts', 'graffito', 'isis', 'nutch', 'joshua', 'brooklyn', 'rave', 'accumulo', 'geode', 'deltacloud', 'wadi', 'gobblin', 'tvm', 'falcon', 'reef', 'qpid', 'awf', 'servicemix', 'amaterasu', 'juice', 'olio', 'ode', 'unomi', 'asterixdb', 'calcite', 'eagle', 'gossip', 'phoenix', 'dolphinscheduler', 'alois', 's2graph', 'blur', 'flume', 'beehive', 'hawq', 'mrunit', 'predictionio', 'hcatalog', 'provisionr', 'libcloud', 'pdfbox', 'river', 'zipkin', 'ftpserver', 'madlib', 'oodt', 'knox'}), 'eclipse': ({'RDF4J', 'Bridge.IoT', 'EclEmma', 'SmartHome', 'Tyrus', 'Temurin', 'Activation', 'Authentication', 'Enterprise Beans', 'SWTBot', 'ORB', 'Mail', 'Kiso', 'Bundle Recipes', 'Server Pages', 'Communications Framework', 'ATL', 'GlassFish', 'WebSocket', 'Angus', 'Capella', 'GLSP', 'EE TCK', 'Jersey', 'Yasson', 'Wild Web Developer', 'Amalgam', 'Embedded CDT (C_C++ Development Tools)', 'Accessibility Tools Framework', 'AJDT - AspectJ Development Tools Project', 'Sirius', 'Jetty - Servlet Engine and Http Server', 'Authorization', 'Parallel Tools Platform (PTP)', 'Stable APIs', 'Kitalpha', 'Tools for Faces', 'Wakaama', 'Mylyn', 'Mosquitto', 'Edje', 'Cargo Tracker', 'Servlet', 'Ponte', 'Nebula NatTable', 'Graphical Editing Framework (GEF)', 'Lyo', 'EGerrit', 'JGit: Java implementation of Git', 'Maven Integration - m2eclipse', 'Batch', 'Remote Application Platform', 'Virgo', 'EMF Parsley', 'XML Web Services', 'BIRT (Business Intelligence and Reporting Tools)', 'EMF Compare', 'Dynamic Languages Toolkit', 'Persistence', 'Collections', 'Ecore Tools', 'Memory Analyzer', 'Generation Factories (EGF)', 'CDT (C_C++ Development Tooling)', 'Equinox', 'Concurrency', 'VIATRA', 'JSON Processing', 'SUMO', 'e(fx)clipse', 'Sprotty', 'Connectors', 'Contexts and Dependency Injection', 'OpenMQ', 'Validation', 'Annotations', 'WaSP', 'Transactions', 'EGit: Git Integration for Eclipse', 'PHP Development Tools', 'Paho', 'Interceptors', 'Acceleo', 'GeoMesa', 'MDT UML2', 'Kapua', 'Orion', 'EMF Client Platform', 'EclipseLink', 'Keyple', 'Linux Tools', 'Implementation of JAXB', 'Buildship: Plug-ins for Gradle', 'Tools for Cloud Foundry', 'Hono', 'Trace Compass', 'Expression Language', 'iceoryx', 'Ditto', 'EE Platform', 'Mojarra', 'RCP Testing Tool', 'JSON Binding', 'Tangle Marketplaces', 'WindowBuilder', 'MoDisco', 'Theia', 'Xtext'}, {'OCL (Object Constraint Language)', 'Concierge', 'Modeling Project', 'Edapt', 'ShellWax', 'Krazo', 'Metro', 'Oomph', 'Security', 'AspectJ', 'EE4J', 'WTP Java EE Tools', 'Passage', 'Dirigible', 'RESTful Web Services', 'EMFStore', 'Grizzly', 'Standard Tag Library', 'Kura', 'Ceylon', 'Modeling Workflow Engine', 'XML Binding', 'Golo', 'Spatial4j', 'JKube', 'Scout', 'Marketplace Client', 'Soteria', 'SW360antenna', 'Leshan', 'Epsilon'}), 'osgeo': ({'geos', 'postgis', 'pdal', 'geoserver', 'geonetwork', 'openlayers', 'osgeolive', 'get-it', 'geowave', 'geomajas', 'pywps', 'istsos', 'mapserver', 'geonode', 'gisquick', 'ossim'}, {'pycsw', 'deegree', 'geopaparazzi', 'proj'}), 'github': ({'docker-registry', 'airflow', 'neocomplcache.vim', 'component', 'tensorflow', 'calipso', 'meteor-up', 'mojito', 'famous', 'ActionBarSherlock', 'generator-gulp-angular', 'forem', 'kissy', 'baker', 'sstoolkit', 'node'}, {'social-app-django', 'inherited_resources', 'busybox', 'django-social-auth', 'scripted'})}

***
## Inference on the Median Folds

In [8]:
def train_helper(m: TimeSeriesModel, X, y):
    # track losses
    losses = {}
    test_losses = {}
    best_loss = float("inf")
    best_epoch = 0
    patience = 10
    TOLERANCE = 1e-4
    
    # initialize optimizer and scheduler
    m.optimizer = torch.optim.AdamW(
        m.model.parameters(),
        lr=m.hyperparams["learning_rate"],
        weight_decay=0.01
    )
    m.scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        m.optimizer, mode="min", factor=0.5, patience=10
    )

    m.loss_fc = FocalLoss(alpha=0.5, gamma=2.0)

    # Training loop
    for epoch in range(m.hyperparams["num_epochs"]):
        m.model.train()
        losses[epoch] = []

        # stochastic GD
        for data, target in tqdm(list(zip(X, y))):
            # shape into (B --> 1, ntimesteps, nfeatures)
            data = data.to(m.device).reshape(1, data.shape[0], -1)
            target = target.to(m.device).to(torch.float32)

            # forward pass
            pred = m.model.predict(data)[..., 1].to(torch.float32)

            # compute loss (Focal Loss)
            loss = m.loss_fc(pred, target)
            
            # backward pass
            m.optimizer.zero_grad()
            loss.backward()

            # grad clipping
            torch.nn.utils.clip_grad_norm_(m.model.parameters(), max_norm=1.0)

            # step the optimizer
            m.optimizer.step()

            # loss tracking
            losses[epoch].append(loss.item())

        # mean loss
        losses[epoch] = np.mean(losses[epoch])

        # logging
        current_lr = m.optimizer.param_groups[0]["lr"]
        log(f"Epoch [{epoch + 1}/{m.hyperparams['num_epochs']}] | "
            f"Loss: {losses[epoch]:.4f}, "
            f"LR: {current_lr:.6f}", "log")

        # lr scheduling
        if m.scheduler is not None:
            m.scheduler.step(losses[epoch])

        # early stopping protocol
        avg_loss = losses[epoch]

        if avg_loss < best_loss - TOLERANCE:
            best_loss = avg_loss
            best_model_weights = copy.deepcopy(m.model.state_dict())      
            patience = 10
            best_epoch = epoch
        else:
            patience -= 1
            if patience == 0:
                log("Early stopping triggered. Loading best model weights.", "log")
                m.model.load_state_dict(best_model_weights)
                break

    # check for divergence
    if np.isnan(sorted(losses.items(), reverse=True)[0][1]) or np.isinf(sorted(losses.items(), reverse=True)[0][1]):
        log("NaN or Inf loss generated, i.e. failed to converge: ignoring and exiting", "error")

    log("Training completed.", "log")

    print(f"Model Name: {m.model_arch}")
    print(f"Input size: {m.hyperparams['input_size']}")
    print(f"Hidden size: {m.hyperparams['hidden_size']}")
    print(f"Number of layers: {m.hyperparams['num_layers']}")
    print(f"Shape of X_train: {X[2].shape}")

In [9]:
def netdata_inference(nd: NetData, model: TimeSeriesModel, test_set: set[str]):
    """
    Inference on the test set of the NetData
    """
    
    # tracker
    predictions = dict()
    predictions["project"] = list()
    predictions["prediction"] = list()
    predictions["target"] = list()
    
    # eval
    model.model.eval()
    with torch.no_grad():
        # iterate projects
        for proj_name, X in nd.data_dict.items():
            # skip
            if proj_name not in test_set:
                continue
            
            # convert to tensor
            X = torch.tensor(X).to(model.device)
            X = X.reshape(1, X.shape[0], -1)
            y_true = (
                "graduated" if proj_name in nd.project_status["graduated"] else
                ("retired" if proj_name in nd.project_status["retired"] else "incubating")
            )
            
            # predictions
            out = model.model(X)
            pred_label = torch.argmax(out, dim=1)
            y_pred = pred_label.cpu().numpy()[0]
            y_pred = "graduated" if y_pred == 1 else "retired"
            
            # update trackers
            predictions["project"].append(proj_name)
            predictions["prediction"].append(y_pred)
            predictions["target"].append(y_true)
    
    # export
    return predictions

def fold_inference(inc: str, folds: dict[str, tuple[set[str], set[str]]], model_arch: str="BLSTM", **kwargs):
    """
    Trains a model on the given train projects and outputs labels for all test
    projects.
    """
    
    # build the train and test sets for all incubators
    nds = {
        i: NetData(
            incubator=i,
            split_set={"train": folds[i][0], "test": folds[i][1]},
            is_train="both",
            verbose=False,
        )
        for i in incs
    }
    
    # setup model & train on the train set
    model = TimeSeriesModel(
        model_arch=model_arch,
        **kwargs
    )
    train_helper(
        model,
        X=nds[inc].tensors["train"]["x"],
        y=nds[inc].tensors["train"]["y"],
    )
    
    # inference on each project in the nd
    return {
        i: netdata_inference(nds[i], model, test_set=folds[i][1])
        for i in incs
    }

In [10]:
# grab pred results
res = {
    inc: fold_inference(inc, median_folds, model_archs[inc])
    for inc in incs
}

Log [0.0h, 0.0m, 0.359s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data

/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.027s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.106s]> Generating tensors

<Tensor Info For Apache>

100%|██████████| 263/263 [00:00<00:00, 11057.56it/s]
100%|██████████| 263/263 [00:00<00:00, 75560.10it/s]

Log [0.0h, 0.0m, 0.032s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.011s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup

/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.039s]> Generating tensors

<Tensor Info For Eclipse>

100%|██████████| 139/139 [00:00<00:00, 20040.85it/s]
100%|██████████| 139/139 [00:00<00:00, 53962.26it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.014s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.004s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Osgeo>

100%|██████████| 24/24 [00:00<00:00, 12593.93it/s]
100%|██████████| 24/24 [00:00<00:00, 56048.61it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.007s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.008s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Github>

100%|██████████| 21/21 [00:00<00:00, 7639.90it/s]
100%|██████████| 21/21 [00:00<00:00, 14385.17it/s]

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>

100%|██████████| 211/211 [00:01<00:00, 158.58it/s]

Log [0.0h, 0.0m, 1.335s]> Epoch [1/100] | loss: 0.0500, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 158.98it/s]

Log [0.0h, 0.0m, 1.331s]> Epoch [2/100] | loss: 0.0474, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.65it/s]

Log [0.0h, 0.0m, 1.325s]> Epoch [3/100] | loss: 0.0356, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.54it/s]

Log [0.0h, 0.0m, 1.317s]> Epoch [4/100] | loss: 0.0321, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 161.53it/s]

Log [0.0h, 0.0m, 1.310s]> Epoch [5/100] | loss: 0.0333, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 167.67it/s]

Log [0.0h, 0.0m, 1.260s]> Epoch [6/100] | loss: 0.0317, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 157.84it/s]

Log [0.0h, 0.0m, 1.341s]> Epoch [7/100] | loss: 0.0312, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.39it/s]

Log [0.0h, 0.0m, 1.319s]> Epoch [8/100] | loss: 0.0312, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.12it/s]

Log [0.0h, 0.0m, 1.353s]> Epoch [9/100] | loss: 0.0312, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 158.53it/s]

Log [0.0h, 0.0m, 1.333s]> Epoch [10/100] | loss: 0.0312, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 159.16it/s]

Log [0.0h, 0.0m, 1.328s]> Epoch [11/100] | loss: 0.0312, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.38it/s]

Log [0.0h, 0.0m, 1.351s]> Epoch [12/100] | loss: 0.0312, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 156.29it/s]

Log [0.0h, 0.0m, 1.352s]> Epoch [13/100] | loss: 0.0311, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 154.25it/s]

Log [0.0h, 0.0m, 1.370s]> Epoch [14/100] | loss: 0.0312, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 163.08it/s]

Log [0.0h, 0.0m, 1.295s]> Epoch [15/100] | loss: 0.0311, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.79it/s]

Log [0.0h, 0.0m, 1.314s]> Epoch [16/100] | loss: 0.0311, lr: 0.001000

100%|██████████| 211/211 [00:01<00:00, 160.98it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 1.312s]> Epoch [17/100] | loss: 0.0311, lr: 0.001000
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([15, 14])
Log [0.0h, 0.0m, 0.124s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.011s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.065s]> Generating tensors

<Tensor Info For Apache>

100%|██████████| 263/263 [00:00<00:00, 12298.91it/s]
100%|██████████| 263/263 [00:00<00:00, 61039.28it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.030s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.008s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.034s]> Generating tensors

<Tensor Info For Eclipse>

100%|██████████| 139/139 [00:00<00:00, 20507.52it/s]
100%|██████████| 139/139 [00:00<00:00, 55099.54it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.013s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.003s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Osgeo>

100%|██████████| 24/24 [00:00<00:00, 12747.03it/s]
100%|██████████| 24/24 [00:00<00:00, 55007.27it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.007s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.006s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Github>

100%|██████████| 21/21 [00:00<00:00, 7462.54it/s]
100%|██████████| 21/21 [00:00<00:00, 13515.48it/s]

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Bidirectional Lstm>

100%|██████████| 108/108 [00:00<00:00, 160.96it/s]

Log [0.0h, 0.0m, 0.679s]> Epoch [1/100] | loss: 0.0415, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 158.37it/s]

Log [0.0h, 0.0m, 0.686s]> Epoch [2/100] | loss: 0.0395, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 163.19it/s]

Log [0.0h, 0.0m, 0.665s]> Epoch [3/100] | loss: 0.0347, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 155.63it/s]

Log [0.0h, 0.0m, 0.697s]> Epoch [4/100] | loss: 0.0313, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 162.02it/s]

Log [0.0h, 0.0m, 0.669s]> Epoch [5/100] | loss: 0.0328, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 163.30it/s]

Log [0.0h, 0.0m, 0.663s]> Epoch [6/100] | loss: 0.0336, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 163.40it/s]

Log [0.0h, 0.0m, 0.663s]> Epoch [7/100] | loss: 0.0317, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 171.04it/s]

Log [0.0h, 0.0m, 0.633s]> Epoch [8/100] | loss: 0.0292, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 161.26it/s]

Log [0.0h, 0.0m, 0.673s]> Epoch [9/100] | loss: 0.0276, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 158.92it/s]

Log [0.0h, 0.0m, 0.682s]> Epoch [10/100] | loss: 0.0304, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 158.51it/s]

Log [0.0h, 0.0m, 0.683s]> Epoch [11/100] | loss: 0.0350, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 163.63it/s]

Log [0.0h, 0.0m, 0.662s]> Epoch [12/100] | loss: 0.0308, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 164.63it/s]

Log [0.0h, 0.0m, 0.658s]> Epoch [13/100] | loss: 0.0330, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 156.70it/s]

Log [0.0h, 0.0m, 0.692s]> Epoch [14/100] | loss: 0.0311, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 163.97it/s]

Log [0.0h, 0.0m, 0.660s]> Epoch [15/100] | loss: 0.0423, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 167.40it/s]

Log [0.0h, 0.0m, 0.647s]> Epoch [16/100] | loss: 0.0364, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 159.60it/s]

Log [0.0h, 0.0m, 0.678s]> Epoch [17/100] | loss: 0.0361, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 162.17it/s]

Log [0.0h, 0.0m, 0.668s]> Epoch [18/100] | loss: 0.0335, lr: 0.001000

100%|██████████| 108/108 [00:00<00:00, 160.71it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.674s]> Epoch [19/100] | loss: 0.0372, lr: 0.001000
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: BLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([10, 14])
Log [0.0h, 0.0m, 0.112s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.011s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.060s]> Generating tensors

<Tensor Info For Apache>

100%|██████████| 263/263 [00:00<00:00, 20023.63it/s]
100%|██████████| 263/263 [00:00<00:00, 79958.10it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.021s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.009s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.034s]> Generating tensors

<Tensor Info For Eclipse>

100%|██████████| 139/139 [00:00<00:00, 18959.62it/s]
100%|██████████| 139/139 [00:00<00:00, 54273.72it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.013s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.004s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Osgeo>

100%|██████████| 24/24 [00:00<00:00, 8049.84it/s]
100%|██████████| 24/24 [00:00<00:00, 54295.20it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.006s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.006s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.008s]> Generating tensors

<Tensor Info For Github>

100%|██████████| 21/21 [00:00<00:00, 7822.41it/s]
100%|██████████| 21/21 [00:00<00:00, 13569.62it/s]

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>

100%|██████████| 16/16 [00:00<00:00, 29.80it/s]

Log [0.0h, 0.0m, 0.543s]> Epoch [1/100] | loss: 0.1161, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 29.24it/s]

Log [0.0h, 0.0m, 0.550s]> Epoch [2/100] | loss: 0.0809, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.16it/s]

Log [0.0h, 0.0m, 0.593s]> Epoch [3/100] | loss: 0.0758, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.08it/s]

Log [0.0h, 0.0m, 0.617s]> Epoch [4/100] | loss: 0.0667, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.97it/s]

Log [0.0h, 0.0m, 0.597s]> Epoch [5/100] | loss: 0.0460, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.67it/s]

Log [0.0h, 0.0m, 0.582s]> Epoch [6/100] | loss: 0.0589, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.90it/s]

Log [0.0h, 0.0m, 0.555s]> Epoch [7/100] | loss: 0.0502, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.50it/s]

Log [0.0h, 0.0m, 0.563s]> Epoch [8/100] | loss: 0.0431, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.12it/s]

Log [0.0h, 0.0m, 0.573s]> Epoch [9/100] | loss: 0.0528, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.40it/s]

Log [0.0h, 0.0m, 0.608s]> Epoch [10/100] | loss: 0.0401, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.13it/s]

Log [0.0h, 0.0m, 0.572s]> Epoch [11/100] | loss: 0.0399, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.71it/s]

Log [0.0h, 0.0m, 0.602s]> Epoch [12/100] | loss: 0.0399, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.15it/s]

Log [0.0h, 0.0m, 0.592s]> Epoch [13/100] | loss: 0.0398, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.04it/s]

Log [0.0h, 0.0m, 0.593s]> Epoch [14/100] | loss: 0.0398, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 29.07it/s]

Log [0.0h, 0.0m, 0.552s]> Epoch [15/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.16it/s]

Log [0.0h, 0.0m, 0.571s]> Epoch [16/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.80it/s]

Log [0.0h, 0.0m, 0.557s]> Epoch [17/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 26.83it/s]

Log [0.0h, 0.0m, 0.598s]> Epoch [18/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.25it/s]

Log [0.0h, 0.0m, 0.568s]> Epoch [19/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.74it/s]

Log [0.0h, 0.0m, 0.578s]> Epoch [20/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.23it/s]

Log [0.0h, 0.0m, 0.589s]> Epoch [21/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 27.89it/s]

Log [0.0h, 0.0m, 0.575s]> Epoch [22/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 29.44it/s]

Log [0.0h, 0.0m, 0.545s]> Epoch [23/100] | loss: 0.0397, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.99it/s]

Log [0.0h, 0.0m, 0.553s]> Epoch [24/100] | loss: 0.0396, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 28.24it/s]

Log [0.0h, 0.0m, 0.568s]> Epoch [25/100] | loss: 0.0396, lr: 0.001000
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([123, 14])

/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.392s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.012s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.061s]> Generating tensors

<Tensor Info For Apache>

100%|██████████| 263/263 [00:00<00:00, 20449.02it/s]
100%|██████████| 263/263 [00:00<00:00, 95855.23it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.021s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.009s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.033s]> Generating tensors

<Tensor Info For Eclipse>

100%|██████████| 139/139 [00:00<00:00, 20341.52it/s]
100%|██████████| 139/139 [00:00<00:00, 54077.38it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.015s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.004s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.009s]> Generating tensors

<Tensor Info For Osgeo>

100%|██████████| 24/24 [00:00<00:00, 13061.28it/s]
100%|██████████| 24/24 [00:00<00:00, 45079.85it/s]
/mnt/data1/Arjun/pex-forecaster/decalfc/abstractions/netdata.py:388: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data = self.data[self.data["proj_name"].isin(project_subset)].groupby("proj_name").apply(process_group)

Log [0.0h, 0.0m, 0.007s]> Setting up netdata
Log [0.0h, 0.0m, 0.000s]> Reading in/generating data
Log [0.0h, 0.0m, 0.006s]> Generating project status, split
Log [0.0h, 0.0m, 0.000s]> Generating data lookup
Log [0.0h, 0.0m, 0.007s]> Generating tensors

<Tensor Info For Github>

100%|██████████| 21/21 [00:00<00:00, 7934.45it/s]
100%|██████████| 21/21 [00:00<00:00, 13561.26it/s]

<Model Setup>
using ***cpu*** for training...

<Model Chosen :: Dilated Lstm>

100%|██████████| 16/16 [00:00<00:00, 19.14it/s]

Log [0.0h, 0.0m, 0.842s]> Epoch [1/100] | loss: 0.0964, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.04it/s]

Log [0.0h, 0.0m, 0.942s]> Epoch [2/100] | loss: 0.0872, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.42it/s]

Log [0.0h, 0.0m, 0.923s]> Epoch [3/100] | loss: 0.0866, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 18.36it/s]

Log [0.0h, 0.0m, 0.876s]> Epoch [4/100] | loss: 0.0916, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.42it/s]

Log [0.0h, 0.0m, 0.920s]> Epoch [5/100] | loss: 0.0731, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 18.40it/s]

Log [0.0h, 0.0m, 0.872s]> Epoch [6/100] | loss: 0.0732, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 18.45it/s]

Log [0.0h, 0.0m, 0.869s]> Epoch [7/100] | loss: 0.0728, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 19.06it/s]

Log [0.0h, 0.0m, 0.843s]> Epoch [8/100] | loss: 0.0727, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 18.95it/s]

Log [0.0h, 0.0m, 0.846s]> Epoch [9/100] | loss: 0.0727, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.65it/s]

Log [0.0h, 0.0m, 0.908s]> Epoch [10/100] | loss: 0.0727, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.46it/s]

Log [0.0h, 0.0m, 0.920s]> Epoch [11/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.87it/s]

Log [0.0h, 0.0m, 0.897s]> Epoch [12/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 18.39it/s]

Log [0.0h, 0.0m, 0.872s]> Epoch [13/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.54it/s]

Log [0.0h, 0.0m, 0.914s]> Epoch [14/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 18.47it/s]

Log [0.0h, 0.0m, 0.868s]> Epoch [15/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 16.78it/s]

Log [0.0h, 0.0m, 0.956s]> Epoch [16/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 18.22it/s]

Log [0.0h, 0.0m, 0.880s]> Epoch [17/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.78it/s]

Log [0.0h, 0.0m, 0.902s]> Epoch [18/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 17.41it/s]

Log [0.0h, 0.0m, 0.921s]> Epoch [19/100] | loss: 0.0726, lr: 0.001000

100%|██████████| 16/16 [00:00<00:00, 19.54it/s]

Log [0.0h, 0.0m, 0.820s]> Epoch [20/100] | loss: 0.0726, lr: 0.001000
Log [0.0h, 0.0m, 0.000s]> Early stopping triggered. loading best model weights.
Log [0.0h, 0.0m, 0.001s]> Training completed.
Model Name: DLSTM
Input size: 14
Hidden size: 64
Number of layers: 2
Shape of X_train: torch.Size([171, 14])

In [11]:
import pandas as pd

res = {
    inc: {
        i: pd.DataFrame(res[inc][i])
        for i in res[inc]
    }
    for inc in incs
}
res

{'apache': {'apache':              project prediction     target
  0           accumulo  graduated  graduated
  1              alois    retired    retired
  2          amaterasu    retired    retired
  3          asterixdb  graduated  graduated
  4                awf    retired    retired
  5            beehive  graduated  graduated
  6               blur    retired    retired
  7           brooklyn  graduated  graduated
  8            calcite  graduated  graduated
  9            cayenne  graduated  graduated
  10        deltacloud  graduated  graduated
  11  dolphinscheduler  graduated  graduated
  12             eagle  graduated  graduated
  13           echarts  graduated  graduated
  14            falcon  graduated  graduated
  15             flume  graduated  graduated
  16        freemarker  graduated  graduated
  17         ftpserver    retired  graduated
  18             geode  graduated  graduated
  19           gobblin  graduated  graduated
  20            gossip    retired    retired
  21          graffito    retired    retired
  22              hawq  graduated  graduated
  23          hcatalog  graduated  graduated
  24              isis  graduated  graduated
  25            joshua    retired  graduated
  26             juice    retired    retired
  27              knox  graduated  graduated
  28          libcloud  graduated  graduated
  29            madlib  graduated  graduated
  30            mrunit  graduated  graduated
  31             nutch  graduated  graduated
  32               ode  graduated  graduated
  33              olio    retired    retired
  34              oodt  graduated  graduated
  35            pdfbox  graduated  graduated
  36           phoenix  graduated  graduated
  37      predictionio  graduated  graduated
  38        provisionr    retired    retired
  39              qpid  graduated  graduated
  40              rave  graduated  graduated
  41              reef  graduated  graduated
  42             river  graduated  graduated
  43           s2graph    retired    retired
  44        servicemix  graduated  graduated
  45              tajo  graduated  graduated
  46         tinkerpop  graduated  graduated
  47    trafficcontrol  graduated  graduated
  48               tvm  graduated  graduated
  49             unomi  graduated  graduated
  50              wadi    retired    retired
  51            zipkin  graduated    retired,
  'eclipse':                              project prediction     target
  0                            AspectJ    retired  graduated
  1                             Ceylon    retired    retired
  2                          Concierge    retired    retired
  3                          Dirigible  graduated  graduated
  4                               EE4J  graduated  graduated
  5                           EMFStore  graduated  graduated
  6                              Edapt    retired  graduated
  7                            Epsilon  graduated  graduated
  8                               Golo    retired    retired
  9                            Grizzly    retired  graduated
  10                             JKube  graduated  graduated
  11                             Krazo  graduated  graduated
  12                              Kura  graduated  graduated
  13                            Leshan  graduated  graduated
  14                Marketplace Client  graduated  graduated
  15                             Metro    retired  graduated
  16                  Modeling Project  graduated  graduated
  17          Modeling Workflow Engine  graduated  graduated
  18  OCL (Object Constraint Language)  graduated  graduated
  19                             Oomph  graduated  graduated
  20                           Passage  graduated  graduated
  21              RESTful Web Services  graduated  graduated
  22                      SW360antenna    retired    retired
  23                             Scout  graduated  graduated
  24                          Security    retired  graduated
  25                          ShellWax    retired  graduated
  26                           Soteria    retired  graduated
  27                         Spatial4j    retired  graduated
  28              Standard Tag Library    retired  graduated
  29                 WTP Java EE Tools    retired  graduated
  30                       XML Binding    retired  graduated,
  'osgeo':         project prediction     target
  0       deegree  graduated  graduated
  1  geopaparazzi  graduated    retired
  2          proj  graduated  graduated
  3         pycsw    retired  graduated,
  'github':                project prediction     target
  0              busybox    retired  graduated
  1   django-social-auth    retired    retired
  2  inherited_resources    retired    retired
  3             scripted    retired    retired
  4    social-app-django    retired  graduated},
 'eclipse': {'apache':              project prediction     target
  0           accumulo  graduated  graduated
  1              alois  graduated    retired
  2          amaterasu  graduated    retired
  3          asterixdb  graduated  graduated
  4                awf  graduated    retired
  5            beehive  graduated  graduated
  6               blur  graduated    retired
  7           brooklyn  graduated  graduated
  8            calcite  graduated  graduated
  9            cayenne  graduated  graduated
  10        deltacloud  graduated  graduated
  11  dolphinscheduler  graduated  graduated
  12             eagle  graduated  graduated
  13           echarts  graduated  graduated
  14            falcon  graduated  graduated
  15             flume  graduated  graduated
  16        freemarker  graduated  graduated
  17         ftpserver  graduated  graduated
  18             geode  graduated  graduated
  19           gobblin  graduated  graduated
  20            gossip  graduated    retired
  21          graffito  graduated    retired
  22              hawq  graduated  graduated
  23          hcatalog  graduated  graduated
  24              isis  graduated  graduated
  25            joshua  graduated  graduated
  26             juice  graduated    retired
  27              knox  graduated  graduated
  28          libcloud  graduated  graduated
  29            madlib  graduated  graduated
  30            mrunit  graduated  graduated
  31             nutch  graduated  graduated
  32               ode  graduated  graduated
  33              olio  graduated    retired
  34              oodt  graduated  graduated
  35            pdfbox  graduated  graduated
  36           phoenix  graduated  graduated
  37      predictionio  graduated  graduated
  38        provisionr  graduated    retired
  39              qpid  graduated  graduated
  40              rave  graduated  graduated
  41              reef  graduated  graduated
  42             river  graduated  graduated
  43           s2graph  graduated    retired
  44        servicemix  graduated  graduated
  45              tajo  graduated  graduated
  46         tinkerpop  graduated  graduated
  47    trafficcontrol  graduated  graduated
  48               tvm  graduated  graduated
  49             unomi  graduated  graduated
  50              wadi    retired    retired
  51            zipkin  graduated    retired,
  'eclipse':                              project prediction     target
  0                            AspectJ  graduated  graduated
  1                             Ceylon    retired    retired
  2                          Concierge  graduated    retired
  3                          Dirigible  graduated  graduated
  4                               EE4J  graduated  graduated
  5                           EMFStore  graduated  graduated
  6                              Edapt    retired  graduated
  7                            Epsilon  graduated  graduated
  8                               Golo  graduated    retired
  9                            Grizzly  graduated  graduated
  10                             JKube  graduated  graduated
  11                             Krazo  graduated  graduated
  12                              Kura  graduated  graduated
  13                            Leshan  graduated  graduated
  14                Marketplace Client  graduated  graduated
  15                             Metro  graduated  graduated
  16                  Modeling Project  graduated  graduated
  17          Modeling Workflow Engine  graduated  graduated
  18  OCL (Object Constraint Language)  graduated  graduated
  19                             Oomph  graduated  graduated
  20                           Passage  graduated  graduated
  21              RESTful Web Services  graduated  graduated
  22                      SW360antenna  graduated    retired
  23                             Scout  graduated  graduated
  24                          Security  graduated  graduated
  25                          ShellWax  graduated  graduated
  26                           Soteria  graduated  graduated
  27                         Spatial4j  graduated  graduated
  28              Standard Tag Library  graduated  graduated
  29                 WTP Java EE Tools  graduated  graduated
  30                       XML Binding  graduated  graduated,
  'osgeo':         project prediction     target
  0       deegree  graduated  graduated
  1  geopaparazzi  graduated    retired
  2          proj  graduated  graduated
  3         pycsw  graduated  graduated,
  'github':                project prediction     target
  0              busybox  graduated  graduated
  1   django-social-auth  graduated    retired
  2  inherited_resources  graduated    retired
  3             scripted  graduated    retired
  4    social-app-django  graduated  graduated},
 'osgeo': {'apache':              project prediction     target
  0           accumulo  graduated  graduated
  1              alois    retired    retired
  2          amaterasu    retired    retired
  3          asterixdb  graduated  graduated
  4                awf  graduated    retired
  5            beehive  graduated  graduated
  6               blur    retired    retired
  7           brooklyn  graduated  graduated
  8            calcite  graduated  graduated
  9            cayenne    retired  graduated
  10        deltacloud  graduated  graduated
  11  dolphinscheduler  graduated  graduated
  12             eagle  graduated  graduated
  13           echarts  graduated  graduated
  14            falcon  graduated  graduated
  15             flume  graduated  graduated
  16        freemarker    retired  graduated
  17         ftpserver    retired  graduated
  18             geode  graduated  graduated
  19           gobblin  graduated  graduated
  20            gossip    retired    retired
  21          graffito    retired    retired
  22              hawq  graduated  graduated
  23          hcatalog  graduated  graduated
  24              isis  graduated  graduated
  25            joshua  graduated  graduated
  26             juice  graduated    retired
  27              knox  graduated  graduated
  28          libcloud  graduated  graduated
  29            madlib  graduated  graduated
  30            mrunit  graduated  graduated
  31             nutch  graduated  graduated
  32               ode  graduated  graduated
  33              olio    retired    retired
  34              oodt  graduated  graduated
  35            pdfbox  graduated  graduated
  36           phoenix  graduated  graduated
  37      predictionio  graduated  graduated
  38        provisionr  graduated    retired
  39              qpid  graduated  graduated
  40              rave  graduated  graduated
  41              reef  graduated  graduated
  42             river  graduated  graduated
  43           s2graph    retired    retired
  44        servicemix  graduated  graduated
  45              tajo  graduated  graduated
  46         tinkerpop  graduated  graduated
  47    trafficcontrol  graduated  graduated
  48               tvm  graduated  graduated
  49             unomi    retired  graduated
  50              wadi    retired    retired
  51            zipkin  graduated    retired,
  'eclipse':                              project prediction     target
  0                            AspectJ    retired  graduated
  1                             Ceylon  graduated    retired
  2                          Concierge    retired    retired
  3                          Dirigible    retired  graduated
  4                               EE4J  graduated  graduated
  5                           EMFStore  graduated  graduated
  6                              Edapt    retired  graduated
  7                            Epsilon  graduated  graduated
  8                               Golo    retired    retired
  9                            Grizzly    retired  graduated
  10                             JKube  graduated  graduated
  11                             Krazo    retired  graduated
  12                              Kura  graduated  graduated
  13                            Leshan    retired  graduated
  14                Marketplace Client    retired  graduated
  15                             Metro    retired  graduated
  16                  Modeling Project  graduated  graduated
  17          Modeling Workflow Engine  graduated  graduated
  18  OCL (Object Constraint Language)  graduated  graduated
  19                             Oomph  graduated  graduated
  20                           Passage  graduated  graduated
  21              RESTful Web Services    retired  graduated
  22                      SW360antenna  graduated    retired
  23                             Scout  graduated  graduated
  24                          Security    retired  graduated
  25                          ShellWax  graduated  graduated
  26                           Soteria    retired  graduated
  27                         Spatial4j  graduated  graduated
  28              Standard Tag Library    retired  graduated
  29                 WTP Java EE Tools    retired  graduated
  30                       XML Binding    retired  graduated,
  'osgeo':         project prediction     target
  0       deegree  graduated  graduated
  1  geopaparazzi    retired    retired
  2          proj  graduated  graduated
  3         pycsw  graduated  graduated,
  'github':                project prediction     target
  0              busybox    retired  graduated
  1   django-social-auth    retired    retired
  2  inherited_resources    retired    retired
  3             scripted    retired    retired
  4    social-app-django    retired  graduated},
 'github': {'apache':              project prediction     target
  0           accumulo    retired  graduated
  1              alois    retired    retired
  2          amaterasu    retired    retired
  3          asterixdb    retired  graduated
  4                awf    retired    retired
  5            beehive    retired  graduated
  6               blur    retired    retired
  7           brooklyn  graduated  graduated
  8            calcite    retired  graduated
  9            cayenne    retired  graduated
  10        deltacloud    retired  graduated
  11  dolphinscheduler  graduated  graduated
  12             eagle  graduated  graduated
  13           echarts  graduated  graduated
  14            falcon    retired  graduated
  15             flume    retired  graduated
  16        freemarker    retired  graduated
  17         ftpserver    retired  graduated
  18             geode  graduated  graduated
  19           gobblin  graduated  graduated
  20            gossip    retired    retired
  21          graffito    retired    retired
  22              hawq  graduated  graduated
  23          hcatalog    retired  graduated
  24              isis    retired  graduated
  25            joshua    retired  graduated
  26             juice    retired    retired
  27              knox    retired  graduated
  28          libcloud    retired  graduated
  29            madlib    retired  graduated
  30            mrunit    retired  graduated
  31             nutch    retired  graduated
  32               ode    retired  graduated
  33              olio    retired    retired
  34              oodt    retired  graduated
  35            pdfbox    retired  graduated
  36           phoenix    retired  graduated
  37      predictionio  graduated  graduated
  38        provisionr    retired    retired
  39              qpid  graduated  graduated
  40              rave    retired  graduated
  41              reef    retired  graduated
  42             river    retired  graduated
  43           s2graph    retired    retired
  44        servicemix    retired  graduated
  45              tajo  graduated  graduated
  46         tinkerpop    retired  graduated
  47    trafficcontrol    retired  graduated
  48               tvm    retired  graduated
  49             unomi    retired  graduated
  50              wadi    retired    retired
  51            zipkin    retired    retired,
  'eclipse':                              project prediction     target
  0                            AspectJ    retired  graduated
  1                             Ceylon    retired    retired
  2                          Concierge    retired    retired
  3                          Dirigible    retired  graduated
  4                               EE4J    retired  graduated
  5                           EMFStore  graduated  graduated
  6                              Edapt    retired  graduated
  7                            Epsilon    retired  graduated
  8                               Golo    retired    retired
  9                            Grizzly    retired  graduated
  10                             JKube    retired  graduated
  11                             Krazo    retired  graduated
  12                              Kura    retired  graduated
  13                            Leshan    retired  graduated
  14                Marketplace Client    retired  graduated
  15                             Metro    retired  graduated
  16                  Modeling Project    retired  graduated
  17          Modeling Workflow Engine    retired  graduated
  18  OCL (Object Constraint Language)    retired  graduated
  19                             Oomph    retired  graduated
  20                           Passage    retired  graduated
  21              RESTful Web Services    retired  graduated
  22                      SW360antenna    retired    retired
  23                             Scout  graduated  graduated
  24                          Security    retired  graduated
  25                          ShellWax    retired  graduated
  26                           Soteria    retired  graduated
  27                         Spatial4j    retired  graduated
  28              Standard Tag Library    retired  graduated
  29                 WTP Java EE Tools    retired  graduated
  30                       XML Binding    retired  graduated,
  'osgeo':         project prediction     target
  0       deegree  graduated  graduated
  1  geopaparazzi    retired    retired
  2          proj    retired  graduated
  3         pycsw    retired  graduated,
  'github':                project prediction     target
  0              busybox    retired  graduated
  1   django-social-auth    retired    retired
  2  inherited_resources    retired    retired
  3             scripted    retired    retired
  4    social-app-django    retired  graduated}}

***
## Organizing Results

In [12]:
def transform_inc_res(inc_res, inc: str):
    for i, df in inc_res.items():
        df["incubator"] = i
        df.rename(columns={"prediction": f"{inc}_pred"}, inplace=True)
        
    return pd.concat(inc_res.values(), ignore_index=True)

In [13]:
r1 = [transform_inc_res(r, i) for i, r in res.items()]
r2 = pd.concat(r1, axis=1, join="outer")
r3 = r2.loc[:, ~r2.columns.duplicated()]
r3

,project,apache_pred,target,incubator,eclipse_pred,osgeo_pred,github_pred
0,accumulo,graduated,graduated,apache,graduated,graduated,retired
1,alois,retired,retired,apache,graduated,retired,retired
2,amaterasu,retired,retired,apache,graduated,retired,retired
3,asterixdb,graduated,graduated,apache,graduated,graduated,retired
4,awf,retired,retired,apache,graduated,graduated,retired
...,...,...,...,...,...,...,...
87,busybox,retired,graduated,github,graduated,retired,retired
88,django-social-auth,retired,retired,github,graduated,retired,retired
89,inherited_resources,retired,retired,github,graduated,retired,retired
90,scripted,retired,retired,github,graduated,retired,retired
91,social-app-django,retired,graduated,github,graduated,retired,retired

In [14]:
df = r3[["incubator", "project", "target", "apache_pred", "eclipse_pred", "osgeo_pred", "github_pred"]]
df.to_csv("triage_results.csv", index=False)

In [15]:
df

,incubator,project,target,apache_pred,eclipse_pred,osgeo_pred,github_pred
0,apache,accumulo,graduated,graduated,graduated,graduated,retired
1,apache,alois,retired,retired,graduated,retired,retired
2,apache,amaterasu,retired,retired,graduated,retired,retired
3,apache,asterixdb,graduated,graduated,graduated,graduated,retired
4,apache,awf,retired,retired,graduated,graduated,retired
...,...,...,...,...,...,...,...
87,github,busybox,graduated,retired,graduated,retired,retired
88,github,django-social-auth,retired,retired,graduated,retired,retired
89,github,inherited_resources,retired,retired,graduated,retired,retired
90,github,scripted,retired,retired,graduated,retired,retired
91,github,social-app-django,graduated,retired,graduated,retired,retired

In [18]:
f = {i: (list(f[0]), list(f[1])) for i, f in median_folds.items()}
f

{'apache': (['skywalking',
   'dubbo',
   'opennlp',
   'photark',
   'ibatis',
   'mesos',
   'batchee',
   'hise',
   'daffodil',
   'manifoldcf',
   'carbondata',
   'curator',
   'shindig',
   'samoa',
   'mod_ftp',
   'droids',
   'rocketmq',
   'zeta',
   'fineract',
   'trafficserver',
   'cloudstack',
   'airflow',
   'parquet',
   'lucy',
   'xap',
   'mrql',
   'trafodion',
   'directmemory',
   'pulsar',
   'ripple',
   'jdo',
   'tamaya',
   'edgent',
   'nuvem',
   'guacamole',
   'stonehenge',
   'devicemap',
   'roller',
   'directory',
   'nmaven',
   'weex',
   'plc4x',
   'superset',
   'iota',
   'derby',
   'bigtop',
   'rya',
   'storm',
   'ctakes',
   'ratis',
   'openjpa',
   'jackrabbit',
   'druid',
   'crunch',
   'concerted',
   'myriad',
   'commonsrdf',
   'lens',
   'struts',
   'thrift',
   'click',
   'etch',
   'empire',
   'imperius',
   'sentry',
   'flex',
   'airavata',
   'stratos',
   'apex',
   'npanday',
   'lokahi',
   'marmotta',
   'solr',
   'servicecomb',
   'vxquery',
   'metamodel',
   'bval',
   'esme',
   'oozie',
   'any23',
   'wicket',
   'subversion',
   'aries',
   'openwebbeans',
   'clerezza',
   'juneau',
   'pig',
   'tephra',
   'singa',
   'pubscribe',
   'sqoop',
   'pivot',
   'sling',
   'lucenenet',
   'iceberg',
   'triplesoup',
   'buildr',
   'olingo',
   'ivy',
   'jclouds',
   'openwhisk',
   'openaz',
   'cmda',
   'bluesky',
   'gearpump',
   'htrace',
   'chukwa',
   'warble',
   'samza',
   'composer',
   'pinot',
   'datasketches',
   'helix',
   'felix',
   'sanselan',
   'cassandra',
   'agila',
   'ignite',
   'ofbiz',
   'giraph',
   'synapse',
   'groovy',
   'drill',
   'datafu',
   'activemq',
   'corinthia',
   'heraldry',
   'wookie',
   'myfaces',
   'systemml',
   'tashi',
   'hama',
   'pirk',
   'odf',
   'kitty',
   'nifi',
   'harmony',
   'shiro',
   'iotdb',
   'allura',
   'sis',
   'oltu',
   'shardingsphere',
   'omid',
   'twill',
   'ace',
   'uima',
   'beam',
   'onami',
   'openoffice',
   'metron',
   'tuscany',
   'horn',
   'celix',
   'sirona',
   'stanbol',
   'mynewt',
   'wave',
   'cordova',
   'quickstep',
   'mnemonic',
   'abdera',
   'netbeans',
   'openmeetings',
   'kato',
   'cxf',
   'atlas',
   'kafka',
   'commons',
   'usergrid',
   'hdt',
   'griffin',
   'aurora',
   'vcl',
   'hudi',
   'yoko',
   'fluo',
   'bloodhound',
   'kudu',
   'stdcxx',
   'zeppelin',
   'muse',
   'couchdb',
   'bookkeeper',
   'ant',
   'slider',
   'streams',
   'jspwiki',
   'ariatosca',
   'tika',
   'gora',
   'kalumet',
   'apisix',
   'tez',
   'syncope',
   'whirr',
   'climate',
   'taverna',
   'impala',
   'ranger',
   'deltaspike',
   's4',
   'adffaces',
   'ambari',
   'spark',
   'johnzon',
   'chemistry',
   'flink',
   'wink',
   'kylin',
   'jena'],
  ['trafficcontrol',
   'cayenne',
   'freemarker',
   'tinkerpop',
   'tajo',
   'echarts',
   'graffito',
   'isis',
   'nutch',
   'joshua',
   'brooklyn',
   'rave',
   'accumulo',
   'geode',
   'deltacloud',
   'wadi',
   'gobblin',
   'tvm',
   'falcon',
   'reef',
   'qpid',
   'awf',
   'servicemix',
   'amaterasu',
   'juice',
   'olio',
   'ode',
   'unomi',
   'asterixdb',
   'calcite',
   'eagle',
   'gossip',
   'phoenix',
   'dolphinscheduler',
   'alois',
   's2graph',
   'blur',
   'flume',
   'beehive',
   'hawq',
   'mrunit',
   'predictionio',
   'hcatalog',
   'provisionr',
   'libcloud',
   'pdfbox',
   'river',
   'zipkin',
   'ftpserver',
   'madlib',
   'oodt',
   'knox']),
 'eclipse': (['RDF4J',
   'Bridge.IoT',
   'EclEmma',
   'SmartHome',
   'Tyrus',
   'Temurin',
   'Activation',
   'Authentication',
   'Enterprise Beans',
   'SWTBot',
   'ORB',
   'Mail',
   'Kiso',
   'Bundle Recipes',
   'Server Pages',
   'Communications Framework',
   'ATL',
   'GlassFish',
   'WebSocket',
   'Angus',
   'Capella',
   'GLSP',
   'EE TCK',
   'Jersey',
   'Yasson',
   'Wild Web Developer',
   'Amalgam',
   'Embedded CDT (C_C++ Development Tools)',
   'Accessibility Tools Framework',
   'AJDT - AspectJ Development Tools Project',
   'Sirius',
   'Jetty - Servlet Engine and Http Server',
   'Authorization',
   'Parallel Tools Platform (PTP)',
   'Stable APIs',
   'Kitalpha',
   'Tools for Faces',
   'Wakaama',
   'Mylyn',
   'Mosquitto',
   'Edje',
   'Cargo Tracker',
   'Servlet',
   'Ponte',
   'Nebula NatTable',
   'Graphical Editing Framework (GEF)',
   'Lyo',
   'EGerrit',
   'JGit: Java implementation of Git',
   'Maven Integration - m2eclipse',
   'Batch',
   'Remote Application Platform',
   'Virgo',
   'EMF Parsley',
   'XML Web Services',
   'BIRT (Business Intelligence and Reporting Tools)',
   'EMF Compare',
   'Dynamic Languages Toolkit',
   'Persistence',
   'Collections',
   'Ecore Tools',
   'Memory Analyzer',
   'Generation Factories (EGF)',
   'CDT (C_C++ Development Tooling)',
   'Equinox',
   'Concurrency',
   'VIATRA',
   'JSON Processing',
   'SUMO',
   'e(fx)clipse',
   'Sprotty',
   'Connectors',
   'Contexts and Dependency Injection',
   'OpenMQ',
   'Validation',
   'Annotations',
   'WaSP',
   'Transactions',
   'EGit: Git Integration for Eclipse',
   'PHP Development Tools',
   'Paho',
   'Interceptors',
   'Acceleo',
   'GeoMesa',
   'MDT UML2',
   'Kapua',
   'Orion',
   'EMF Client Platform',
   'EclipseLink',
   'Keyple',
   'Linux Tools',
   'Implementation of JAXB',
   'Buildship: Plug-ins for Gradle',
   'Tools for Cloud Foundry',
   'Hono',
   'Trace Compass',
   'Expression Language',
   'iceoryx',
   'Ditto',
   'EE Platform',
   'Mojarra',
   'RCP Testing Tool',
   'JSON Binding',
   'Tangle Marketplaces',
   'WindowBuilder',
   'MoDisco',
   'Theia',
   'Xtext'],
  ['OCL (Object Constraint Language)',
   'Concierge',
   'Modeling Project',
   'Edapt',
   'ShellWax',
   'Krazo',
   'Metro',
   'Oomph',
   'Security',
   'AspectJ',
   'EE4J',
   'WTP Java EE Tools',
   'Passage',
   'Dirigible',
   'RESTful Web Services',
   'EMFStore',
   'Grizzly',
   'Standard Tag Library',
   'Kura',
   'Ceylon',
   'Modeling Workflow Engine',
   'XML Binding',
   'Golo',
   'Spatial4j',
   'JKube',
   'Scout',
   'Marketplace Client',
   'Soteria',
   'SW360antenna',
   'Leshan',
   'Epsilon']),
 'osgeo': (['geos',
   'postgis',
   'pdal',
   'geoserver',
   'geonetwork',
   'openlayers',
   'osgeolive',
   'get-it',
   'geowave',
   'geomajas',
   'pywps',
   'istsos',
   'mapserver',
   'geonode',
   'gisquick',
   'ossim'],
  ['pycsw', 'deegree', 'geopaparazzi', 'proj']),
 'github': (['docker-registry',
   'airflow',
   'neocomplcache.vim',
   'component',
   'tensorflow',
   'calipso',
   'meteor-up',
   'mojito',
   'famous',
   'ActionBarSherlock',
   'generator-gulp-angular',
   'forem',
   'kissy',
   'baker',
   'sstoolkit',
   'node'],
  ['social-app-django',
   'inherited_resources',
   'busybox',
   'django-social-auth',
   'scripted'])}

In [ ]:
import json

with open("triage_median_folds.json", "w") as file:
    json.dump(f, file, indent=4)